#!/usr/bin/env bash
set -euo pipefail

# Ensure Go is on PATH when invoked via SSH non-login shell
export PATH="$PATH:/usr/local/go/bin:$HOME/go/bin"

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"

# --- Multi-instance detection ---
# crewship_1 -> instance 1, crewship_2 -> instance 2, etc.
INSTANCE_NUM=$(basename "$PROJECT_DIR" | sed -n 's/^crewship_\([0-9]*\)$/\1/p')
INSTANCE_NUM=${INSTANCE_NUM:-0}

if [[ "$INSTANCE_NUM" -eq 0 ]]; then
  GO_PORT=8080; NEXT_PORT=3001; S=""
else
  GO_PORT=$((8080 + INSTANCE_NUM)); NEXT_PORT=$((3010 + INSTANCE_NUM)); S="-${INSTANCE_NUM}"
fi

NEXT_PID_FILE="/tmp/crewship${S}-next.pid"
GO_PID_FILE="/tmp/crewship${S}-go.pid"
NEXT_LOG="/tmp/crewship${S}-next.log"
GO_LOG="/tmp/crewship${S}-go.log"

DATA_DIR="/tmp/crewship${S}-data"
LOG_PATH="/tmp/crewship${S}-logs"
STATE_DIR="/tmp/crewship${S}-state"
SOCKET_PATH="/tmp/crewship${S}.sock"
CONTAINER_NETWORK="crewship${S}-agents"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

log()  { echo -e "${CYAN}[crewship${S}]${NC} $*"; }
ok()   { echo -e "${GREEN}[crewship${S}]${NC} $*"; }
warn() { echo -e "${YELLOW}[crewship${S}]${NC} $*"; }
err()  { echo -e "${RED}[crewship${S}]${NC} $*" >&2; }

is_running() {
  local pid_file="$1"
  if [[ -f "$pid_file" ]]; then
    local pid
    pid=$(cat "$pid_file")
    if kill -0 "$pid" 2>/dev/null; then
      echo "$pid"
      return 0
    fi
    rm -f "$pid_file"
  fi
  return 1
}

# Portable timeout: macOS ships without GNU timeout; Homebrew provides gtimeout.
TIMEOUT_CMD="$(command -v timeout 2>/dev/null || command -v gtimeout 2>/dev/null || true)"
if [[ -z "$TIMEOUT_CMD" ]]; then
  warn "timeout/gtimeout not found; install GNU coreutils for Docker detection timeouts"
fi

port_in_use() {
  # Use /dev/tcp probe instead of lsof — lsof scans all FDs system-wide
  # and is extremely slow on external SSD volumes (10-30s vs <0.1s).
  (echo >/dev/tcp/127.0.0.1/"$1") 2>/dev/null || nc -z 127.0.0.1 "$1" 2>/dev/null
}

detect_db_mode() {
  if [[ -f "$PROJECT_DIR/.env.local" ]]; then
    local db_url
    db_url=$(grep -E '^DATABASE_URL=' "$PROJECT_DIR/.env.local" | head -1 | cut -d'=' -f2- | tr -d '"' || true)
    if [[ "$db_url" == postgresql://* ]] || [[ "$db_url" == postgres://* ]]; then
      echo "postgresql"
      return
    fi
  fi
  echo "sqlite"
}

check_prerequisites() {
  local missing=0

  if [[ ! -f "$PROJECT_DIR/.env.local" ]]; then
    err ".env.local not found -- copy from .env.example and fill in values"
    missing=1
  fi

  for cmd in node pnpm go; do
    if ! command -v "$cmd" &>/dev/null; then
      err "$cmd is not installed"
      missing=1
    fi
  done

  # Docker is only required if agents will be run
  if ! command -v docker &>/dev/null; then
    warn "docker is not installed -- agent containers will not work"
  fi

  if [[ $missing -ne 0 ]]; then
    err "Prerequisites check failed"
    exit 1
  fi
}

# Generate/update .env.local with instance-specific ports and paths.
# Preserves existing secrets (NEXTAUTH_SECRET, ENCRYPTION_KEY, DATABASE_URL, etc.)
generate_env_local() {
  local env_file="$PROJECT_DIR/.env.local"

  if [[ ! -f "$env_file" ]]; then
    return
  fi

  # Keys managed by this function (will be replaced/added).
  # NEXT_PUBLIC_WS_URL is listed so it gets stripped from old .env.local
  # files but is NOT re-emitted — the dev server proxy makes it unnecessary.
  local managed_keys=(
    NEXT_PUBLIC_GO_PORT
    NEXT_PUBLIC_WS_URL  # removed from output but still stripped to clean up old values
    NEXTAUTH_URL
    CREWSHIP_PORT
    CREWSHIP_SOCKET_PATH
    CREWSHIP_CONTAINER_NETWORK
    CREWSHIP_CONTAINER_PREFIX
    CREWSHIP_STORAGE_BASE_PATH
    CREWSHIP_LOG_PATH
    CREWSHIP_BOLT_PATH
    CREWSHIP_NEXTJS_URL
  )

  # Read existing file, stripping managed keys
  local tmp_file
  tmp_file=$(mktemp)
  local key
  while IFS= read -r line || [[ -n "$line" ]]; do
    local skip=false
    for key in "${managed_keys[@]}"; do
      if [[ "$line" == "${key}="* ]]; then
        skip=true
        break
      fi
    done
    if [[ "$skip" == false ]]; then
      echo "$line" >> "$tmp_file"
    fi
  done < "$env_file"

  # Remove trailing blank lines, then add one
  sed -i '' -e :a -e '/^\n*$/{$d;N;ba' -e '}' "$tmp_file" 2>/dev/null || true
  echo "" >> "$tmp_file"

  # Append managed keys
  {
    echo "# --- Auto-generated by dev.sh (instance${S:-0}) ---"
    echo "NEXT_PUBLIC_GO_PORT=${GO_PORT}"
    # NEXT_PUBLIC_WS_URL intentionally omitted — frontend auto-detects
    # from window.location.hostname, which works for both local and remote access.
    echo "NEXTAUTH_URL=http://localhost:${NEXT_PORT}"
    echo "CREWSHIP_PORT=${GO_PORT}"
    echo "CREWSHIP_SOCKET_PATH=${SOCKET_PATH}"
    echo "CREWSHIP_CONTAINER_NETWORK=${CONTAINER_NETWORK}"
    echo "CREWSHIP_CONTAINER_PREFIX=crewship${S}"
    echo "CREWSHIP_STORAGE_BASE_PATH=${DATA_DIR}"
    echo "CREWSHIP_LOG_PATH=${LOG_PATH}"
    echo "CREWSHIP_BOLT_PATH=${STATE_DIR}/state.db"
    echo "CREWSHIP_NEXTJS_URL=http://localhost:${NEXT_PORT}"
  } >> "$tmp_file"

  mv "$tmp_file" "$env_file"
}

start_postgres() {
  local db_mode
  db_mode=$(detect_db_mode)

  if [[ "$db_mode" != "postgresql" ]]; then
    ok "Using SQLite (no PostgreSQL needed)"
    return
  fi

  local pg_port=$((5432 + INSTANCE_NUM))
  log "Starting PostgreSQL on :$pg_port (DATABASE_URL points to PostgreSQL)..."
  if COMPOSE_PROJECT_NAME="crewship${S}" CREWSHIP_PG_PORT="$pg_port" \
      docker compose -f "$PROJECT_DIR/docker/docker-compose.yml" ps --format '{{.Status}}' 2>/dev/null | grep -qi "up"; then
    ok "PostgreSQL already running"
  else
    COMPOSE_PROJECT_NAME="crewship${S}" CREWSHIP_PG_PORT="$pg_port" \
      docker compose -f "$PROJECT_DIR/docker/docker-compose.yml" up -d
    ok "PostgreSQL started on :$pg_port"
  fi
}

start_go() {
  if pid=$(is_running "$GO_PID_FILE"); then
    ok "crewship already running (pid $pid)"
    return
  fi

  if port_in_use "$GO_PORT"; then
    err "Port $GO_PORT already in use -- stop the process first"
    return 1
  fi

  log "Starting crewship on :$GO_PORT..."
  mkdir -p "$DATA_DIR" "$LOG_PATH" "$STATE_DIR"

  # Build first (cached builds are <1s, cold ~9s on external SSD).
  # "go run" compiles on every start and the compilation time eats into
  # the health-check budget, causing false "timed out" warnings.
  local binary="/tmp/crewship${S}-dev"
  log "Building crewship..."
  if ! (cd "$PROJECT_DIR" && go build -o "$binary" ./cmd/crewship) 2>&1; then
    err "Go build failed -- check errors above"
    return 1
  fi

  # Build the standalone sidecar binary + stage entrypoint.sh alongside the
  # crewship binary so the docker provider's autodetect can pick them up and
  # bind-mount into crew containers (CRE-123 Phase 1). Place them next to the
  # dev binary so os.Executable()-based detection resolves correctly.
  local bin_dir
  bin_dir="$(dirname "$binary")"
  log "Building crewship-sidecar..."
  if ! (cd "$PROJECT_DIR" && CGO_ENABLED=0 go build -ldflags="-s -w" -o "${bin_dir}/crewship-sidecar" ./cmd/crewship-sidecar) 2>&1; then
    err "Sidecar build failed -- check errors above"
    return 1
  fi
  cp "$PROJECT_DIR/docker/agent-runtime/entrypoint.sh" "${bin_dir}/entrypoint.sh"
  chmod +x "${bin_dir}/entrypoint.sh"

  (
    cd "$PROJECT_DIR"
    set -a && . ./.env.local && set +a
    export CREWSHIP_LOG_LEVEL=debug
    # Auto-detect container runtime; fall back to --no-docker if none found
    # Supports Docker, Podman, and Apple Containers (macOS 26+)
    export CREWSHIP_CONTAINER_PROVIDER="${CREWSHIP_CONTAINER_PROVIDER:-auto}"
    local has_runtime=false
    if [[ -n "$TIMEOUT_CMD" ]] && { "$TIMEOUT_CMD" 3 docker info &>/dev/null || "$TIMEOUT_CMD" 3 podman info &>/dev/null; }; then
      has_runtime=true
    elif [[ -z "$TIMEOUT_CMD" ]] && { docker info &>/dev/null 2>&1 || podman info &>/dev/null 2>&1; }; then
      has_runtime=true
    fi
    # Check Apple Containers CLI (macOS 26+)
    if ! $has_runtime && command -v container &>/dev/null && container system status &>/dev/null 2>&1; then
      has_runtime=true
    fi
    if $has_runtime; then
      exec "$binary" start
    else
      exec "$binary" start --no-docker
    fi
  ) > "$GO_LOG" 2>&1 &

  echo $! > "$GO_PID_FILE"

  local attempts=0
  while [[ $attempts -lt 15 ]]; do
    if curl -sf http://localhost:$GO_PORT/api/health >/dev/null 2>&1; then
      ok "crewship started (pid $(cat "$GO_PID_FILE"))"
      return
    fi
    sleep 1
    attempts=$((attempts + 1))
  done

  warn "crewship started but health check timed out -- check $GO_LOG"
}

start_next() {
  if pid=$(is_running "$NEXT_PID_FILE"); then
    ok "Next.js already running (pid $pid)"
    return
  fi

  if port_in_use "$NEXT_PORT"; then
    err "Port $NEXT_PORT already in use -- stop the process first"
    return 1
  fi

  log "Starting Next.js on :$NEXT_PORT..."

  (
    cd "$PROJECT_DIR"
    exec node dev-server.mjs "$NEXT_PORT"
  ) > "$NEXT_LOG" 2>&1 &

  echo $! > "$NEXT_PID_FILE"

  local attempts=0
  while [[ $attempts -lt 20 ]]; do
    if curl -sf -o /dev/null http://localhost:$NEXT_PORT 2>/dev/null; then
      ok "Next.js started (pid $(cat "$NEXT_PID_FILE"))"
      return
    fi
    sleep 1
    attempts=$((attempts + 1))
  done

  warn "Next.js started but readiness check timed out -- check $NEXT_LOG"
}

kill_tree() {
  local pid="$1"
  local children
  children=$(pgrep -P "$pid" 2>/dev/null || true)
  for child in $children; do
    kill_tree "$child"
  done
  kill "$pid" 2>/dev/null || true
}

stop_service() {
  local name="$1" pid_file="$2" port="$3"

  if pid=$(is_running "$pid_file"); then
    log "Stopping $name (pid $pid)..."
    kill_tree "$pid"
    local attempts=0
    while kill -0 "$pid" 2>/dev/null && [[ $attempts -lt 10 ]]; do
      sleep 0.5
      attempts=$((attempts + 1))
    done
    if kill -0 "$pid" 2>/dev/null; then
      kill -9 "$pid" 2>/dev/null || true
    fi
    rm -f "$pid_file"
  fi

  if port_in_use "$port"; then
    # Use fuser (fast) or fall back to lsof with timeout to avoid SSD hangs
    local orphan_pids
    orphan_pids=$(fuser "$port/tcp" 2>/dev/null | tr -s ' ' || true)
    if [[ -z "$orphan_pids" && -n "$TIMEOUT_CMD" ]]; then
      orphan_pids=$("$TIMEOUT_CMD" 5 lsof -ti:"$port" 2>/dev/null || true)
    elif [[ -z "$orphan_pids" ]]; then
      orphan_pids=$(lsof -ti:"$port" 2>/dev/null || true)
    fi
    for orphan_pid in $orphan_pids; do
      kill "$orphan_pid" 2>/dev/null || true
    done
    sleep 1
    if port_in_use "$port"; then
      orphan_pids=$(fuser "$port/tcp" 2>/dev/null | tr -s ' ' || true)
      if [[ -z "$orphan_pids" && -n "$TIMEOUT_CMD" ]]; then
        orphan_pids=$("$TIMEOUT_CMD" 5 lsof -ti:"$port" 2>/dev/null || true)
      elif [[ -z "$orphan_pids" ]]; then
        orphan_pids=$(lsof -ti:"$port" 2>/dev/null || true)
      fi
      for orphan_pid in $orphan_pids; do
        kill -9 "$orphan_pid" 2>/dev/null || true
      done
    fi
  fi

  ok "$name stopped"
}

cmd_start() {
  check_prerequisites

  # Install git pre-commit hook (idempotent, auto-skips if already installed)
  # See scripts/install-hooks.sh — runs gitleaks + golangci-lint on changed files.
  if [[ -x "$PROJECT_DIR/scripts/install-hooks.sh" ]]; then
    "$PROJECT_DIR/scripts/install-hooks.sh" >/dev/null 2>&1 || true
  fi

  echo -e "${BOLD}Crewship Dev Environment${NC}"
  if [[ "$INSTANCE_NUM" -gt 0 ]]; then
    echo -e "${BOLD}Instance ${INSTANCE_NUM}${NC} (Go :${GO_PORT}, Next.js :${NEXT_PORT})"
  fi
  echo "========================"
  echo ""

  generate_env_local

  local db_mode
  db_mode=$(detect_db_mode)
  echo -e "  Database:  ${CYAN}$db_mode${NC}"
  echo ""
  start_postgres
  start_go
  start_next
  echo ""
  ok "All services started"
  echo -e "  Frontend:  ${CYAN}http://localhost:$NEXT_PORT${NC}"
  echo -e "  Backend:   ${CYAN}http://localhost:$GO_PORT${NC}"
  echo -e "  WebSocket: ${CYAN}ws://localhost:$GO_PORT/ws${NC}"
  echo -e "  Logs:      ${CYAN}./dev.sh logs${NC}"
}

cmd_stop() {
  echo -e "${BOLD}Stopping Crewship${S}...${NC}"
  stop_service "Next.js" "$NEXT_PID_FILE" "$NEXT_PORT"
  stop_service "crewship" "$GO_PID_FILE" "$GO_PORT"
  local db_mode
  db_mode=$(detect_db_mode)
  if [[ "$db_mode" == "postgresql" ]]; then
    ok "Stopped (PostgreSQL left running)"
  else
    ok "Stopped"
  fi
}

cmd_restart() {
  cmd_stop
  echo ""
  cmd_start
}

cmd_status() {
  echo -e "${BOLD}Crewship Dev Environment${NC}"
  if [[ "$INSTANCE_NUM" -gt 0 ]]; then
    echo -e "${BOLD}Instance ${INSTANCE_NUM}${NC} (Go :${GO_PORT}, Next.js :${NEXT_PORT})"
  fi
  echo "========================"

  local db_mode
  db_mode=$(detect_db_mode)

  if [[ "$db_mode" == "postgresql" ]]; then
    local pg_port=$((5432 + INSTANCE_NUM))
    if COMPOSE_PROJECT_NAME="crewship${S}" CREWSHIP_PG_PORT="$pg_port" \
        docker compose -f "$PROJECT_DIR/docker/docker-compose.yml" ps --format '{{.Status}}' 2>/dev/null | grep -qi "up"; then
      echo -e "  PostgreSQL:  ${GREEN}running${NC} (port $pg_port)"
    else
      echo -e "  PostgreSQL:  ${RED}stopped${NC}"
    fi
  else
    echo -e "  SQLite:      ${GREEN}file:./crewship.db${NC}"
  fi

  if pid=$(is_running "$GO_PID_FILE"); then
    if curl -sf http://localhost:$GO_PORT/api/health >/dev/null 2>&1; then
      echo -e "  crewship:    ${GREEN}running${NC} (pid $pid)"
    else
      echo -e "  crewship:    ${YELLOW}starting${NC} (pid $pid)"
    fi
  elif port_in_use "$GO_PORT"; then
    echo -e "  crewship:    ${YELLOW}running (orphan on :$GO_PORT)${NC}"
  else
    echo -e "  crewship:    ${RED}stopped${NC}"
  fi

  if pid=$(is_running "$NEXT_PID_FILE"); then
    echo -e "  Next.js:     ${GREEN}running${NC} (pid $pid, port $NEXT_PORT)"
  elif port_in_use "$NEXT_PORT"; then
    echo -e "  Next.js:     ${YELLOW}running (orphan on :$NEXT_PORT)${NC}"
  else
    echo -e "  Next.js:     ${RED}stopped${NC}"
  fi

  echo ""
  echo -e "  Frontend:    http://localhost:$NEXT_PORT"
  echo -e "  Backend:     http://localhost:$GO_PORT"
  echo -e "  WebSocket:   ws://localhost:$GO_PORT/ws"
  echo -e "  IPC Socket:  $SOCKET_PATH"
}

cmd_logs() {
  tail -f "$GO_LOG" "$NEXT_LOG" 2>/dev/null
}

cmd_logs_go() {
  tail -f "$GO_LOG" 2>/dev/null
}

cmd_logs_next() {
  tail -f "$NEXT_LOG" 2>/dev/null
}

cmd_nuke() {
  echo -e "${BOLD}${RED}Factory Reset — Crewship${S}${NC}"
  echo "This will destroy ALL local data:"
  echo "  - SQLite database (./crewship.db)"
  echo "  - Agent output, workspace, crew data ($DATA_DIR)"
  echo "  - Bolt state ($STATE_DIR)"
  echo "  - Conversations ($DATA_DIR/conversations)"
  echo "  - Log files ($LOG_PATH)"
  echo "  - Docker containers (crewship${S}-team-*)"
  echo "  - Docker network ($CONTAINER_NETWORK)"
  echo ""

  if [[ "${2:-}" != "--yes" ]]; then
    read -rp "Type 'nuke' to confirm: " confirm
    if [[ "$confirm" != "nuke" ]]; then
      err "Aborted."
      exit 1
    fi
  fi

  echo ""
  # 1. Stop services
  log "Stopping services..."
  cmd_stop 2>/dev/null || true

  # 2. Remove Docker containers for this instance
  log "Removing Docker containers..."
  local docker_cmd
  docker_cmd=$(command -v docker 2>/dev/null || echo "$HOME/.docker/bin/docker")
  if [[ -x "$docker_cmd" ]] || command -v docker &>/dev/null; then
    local prefix="crewship${S}-team-"
    local containers
    containers=$($docker_cmd ps -a --filter "name=${prefix}" --format '{{.ID}}' 2>/dev/null || true)
    if [[ -n "$containers" ]]; then
      echo "$containers" | xargs $docker_cmd rm -f 2>/dev/null || true
      ok "Containers removed"
    else
      ok "No containers to remove"
    fi

    # Remove network
    if $docker_cmd network inspect "$CONTAINER_NETWORK" &>/dev/null; then
      $docker_cmd network rm "$CONTAINER_NETWORK" 2>/dev/null || true
      ok "Network $CONTAINER_NETWORK removed"
    fi
  else
    warn "Docker not available — skipping container cleanup"
  fi

  # 3. Remove data directories
  log "Removing data..."
  rm -rf "$DATA_DIR"
  rm -rf "$STATE_DIR"
  rm -rf "$LOG_PATH"
  rm -f "$SOCKET_PATH"
  ok "Data directories removed"

  # 4. Remove SQLite database
  if [[ -f "$PROJECT_DIR/crewship.db" ]]; then
    rm -f "$PROJECT_DIR/crewship.db"
    rm -f "$PROJECT_DIR/crewship.db-shm"
    rm -f "$PROJECT_DIR/crewship.db-wal"
    ok "SQLite database removed"
  fi

  # 5. Remove log files
  rm -f "$GO_LOG" "$NEXT_LOG"
  rm -f "$GO_PID_FILE" "$NEXT_PID_FILE"
  ok "Logs and PID files cleaned"

  echo ""
  ok "Factory reset complete. Run ${CYAN}./dev.sh start${NC} then ${CYAN}./dev.sh seed${NC} for a fresh environment."
}

cmd_seed() {
  log "Seeding database via CLI..."

  # Health check — ensure the server is running before attempting to seed
  if ! curl -sf "http://localhost:${GO_PORT}/api/health" >/dev/null 2>&1; then
    err "crewship is not running on :${GO_PORT} -- run ./dev.sh start first"
    exit 1
  fi

  # Verify .env.local exists (needed for SEED_* env vars)
  if [[ ! -f "$PROJECT_DIR/.env.local" ]]; then
    err ".env.local not found -- copy from .env.example and fill in values"
    exit 1
  fi

  # Build CLI binary
  log "Building crewship CLI..."
  (cd "$PROJECT_DIR" && go build -o ./crewship ./cmd/crewship/)

  # Source env vars and run seed via CLI (requires running server)
  (
    cd "$PROJECT_DIR"
    set -a && . ./.env.local && set +a
    ./crewship seed --server "http://localhost:${GO_PORT:-8080}"
  )

  ok "Seed complete."
}

case "${1:-help}" in
  start)     cmd_start ;;
  stop)      cmd_stop ;;
  restart)   cmd_restart ;;
  status)    cmd_status ;;
  nuke)      cmd_nuke "$@" ;;
  seed)      cmd_seed ;;
  logs)      cmd_logs ;;
  logs:go)   cmd_logs_go ;;
  logs:next) cmd_logs_next ;;
  *)
    echo "Usage: ./dev.sh {start|stop|restart|status|seed|nuke|logs|logs:go|logs:next}"
    echo ""
    echo "  start     Start crewship + Next.js (+ PostgreSQL if configured)"
    echo "  stop      Stop crewship + Next.js"
    echo "  restart   Stop then start all services"
    echo "  status    Show status of all services"
    echo "  seed      Seed database with demo data (requires running server)"
    echo "  nuke      Factory reset (destroy all data, containers, start fresh)"
    echo "  logs      Tail combined logs"
    echo "  logs:go   Tail crewship logs only"
    echo "  logs:next Tail Next.js logs only"
    if [[ "$INSTANCE_NUM" -gt 0 ]]; then
      echo ""
      echo "  Instance:  ${INSTANCE_NUM} (Go :${GO_PORT}, Next.js :${NEXT_PORT})"
    fi
    exit 1
    ;;
esac
