"use client"

import * as React from "react"
import { Link2 } from "lucide-react"

import { EmptyHint, TableSkeleton } from "./shared"
import type { AgentLite, AgentBindingsMap } from "./types"

// McpEndpointsTab — the per-agent MCP endpoints generated by binding. Each row
// is derived from an agent's Composio binding: Agent → scoped MCP URL (mono,
// truncated) + a "live" badge. Agents without a binding are omitted.
export function McpEndpointsTab({
  agents,
  bindings,
  loading,
}: {
  agents: AgentLite[]
  bindings: AgentBindingsMap
  loading: boolean
}) {
  const rows = React.useMemo(
    () =>
      agents.flatMap((a) =>
        (bindings[a.id] ?? []).map((b) => ({
          key: `${a.id}:${b.toolkit}:${b.user_id}`,
          agent: a,
          binding: b,
        })),
      ),
    [agents, bindings],
  )

  return (
    <section className="space-y-3">
      <h2 className="flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
        <Link2 className="h-3.5 w-3.5" /> MCP endpoints
        <span className="font-normal normal-case tracking-normal text-muted-foreground/70">
          · generated per agent, scoped by user_id
        </span>
      </h2>

      {loading ? (
        <TableSkeleton rows={3} />
      ) : rows.length === 0 ? (
        <EmptyHint text="No MCP endpoints yet. Assign an agent a Composio user in the Agent access tab to generate one." />
      ) : (
        <div className="space-y-2">
          {rows.map(({ key, agent, binding }) => (
            <div
              key={key}
              className="flex items-center justify-between gap-3 rounded-xl border border-white/10 bg-card px-4 py-3"
            >
              <div className="flex min-w-0 items-center gap-2 text-[12px]">
                <span className="font-medium">{agent.name}</span>
                <span className="text-muted-foreground">→</span>
                <span className="truncate font-mono text-[11px] text-muted-foreground">
                  {binding.endpoint || `…?user_id=${binding.user_id}`}
                </span>
              </div>
              <span className="inline-flex shrink-0 items-center gap-1 rounded-full border border-emerald-400/30 bg-emerald-500/[0.08] px-2 py-0.5 text-[10px] text-emerald-400">
                ● live
              </span>
            </div>
          ))}
        </div>
      )}
    </section>
  )
}
