package kinds

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"strings"
	"testing"

	"github.com/crewship-ai/crewship/internal/manifest/internalapi"
)

// fakeClient implements internalapi.Client over a tiny route table.
// One concrete recipe under management at a time is enough — each
// test case configures the slug + installed flag it cares about.
type fakeClient struct {
	wsID string

	// recipes is the catalog the fake "server" exposes. Keyed by
	// slug; values carry the installed flag the GET handlers return.
	recipes map[string]RecipeRemote

	// installCallback runs whenever POST /api/v1/recipes/{slug}/install
	// fires. Tests set this to capture the body the manifest sent.
	installCallback func(slug string, body any)

	// installStatus is the HTTP status the install endpoint returns
	// (defaults to 201).
	installStatus int

	// catalog404 forces the GET /api/v1/recipes/{slug} handler to
	// return 404 — used to test the "recipe slug missing from catalog"
	// path through LookupRecipeRemote.
	catalog404 map[string]bool

	// calls records every HTTP method+path so tests can assert no
	// extraneous traffic was generated by Plan for unchanged cases.
	calls []string
}

func newFakeClient() *fakeClient {
	return &fakeClient{
		wsID:       "ws_test",
		recipes:    map[string]RecipeRemote{},
		catalog404: map[string]bool{},
	}
}

func (f *fakeClient) WorkspaceID() string { return f.wsID }

func (f *fakeClient) record(method, path string) {
	f.calls = append(f.calls, method+" "+path)
}

func jsonResp(status int, v any) *internalapi.Response {
	data, _ := json.Marshal(v)
	return &internalapi.Response{
		StatusCode: status,
		Body:       io.NopCloser(bytes.NewReader(data)),
	}
}

func (f *fakeClient) Get(_ context.Context, path string) (*internalapi.Response, error) {
	f.record("GET", path)
	switch {
	case path == "/api/v1/recipes":
		var out []RecipeRemote
		for _, r := range f.recipes {
			out = append(out, r)
		}
		return jsonResp(200, out), nil
	case strings.HasPrefix(path, "/api/v1/recipes/"):
		slug := strings.TrimPrefix(path, "/api/v1/recipes/")
		if f.catalog404[slug] {
			return jsonResp(404, map[string]any{"error": "Recipe not found"}), nil
		}
		row, ok := f.recipes[slug]
		if !ok {
			return jsonResp(404, map[string]any{"error": "Recipe not found"}), nil
		}
		return jsonResp(200, row), nil
	}
	return jsonResp(404, map[string]any{"error": "not found"}), nil
}

func (f *fakeClient) Post(_ context.Context, path string, body any) (*internalapi.Response, error) {
	f.record("POST", path)
	if strings.HasPrefix(path, "/api/v1/recipes/") && strings.HasSuffix(path, "/install") {
		slug := strings.TrimSuffix(strings.TrimPrefix(path, "/api/v1/recipes/"), "/install")
		if f.installCallback != nil {
			f.installCallback(slug, body)
		}
		// Mutate the fake server's installed flag so re-Planning
		// against the same client returns Unchanged.
		row := f.recipes[slug]
		row.Installed = true
		row.Slug = slug
		f.recipes[slug] = row
		status := f.installStatus
		if status == 0 {
			status = 201
		}
		return jsonResp(status, map[string]any{"crew_slug": "demo"}), nil
	}
	return jsonResp(404, map[string]any{"error": "not found"}), nil
}

func (f *fakeClient) Patch(_ context.Context, _ string, _ any) (*internalapi.Response, error) {
	return jsonResp(404, nil), nil
}

func (f *fakeClient) Put(_ context.Context, _ string, _ any) (*internalapi.Response, error) {
	return jsonResp(404, nil), nil
}

func (f *fakeClient) Delete(_ context.Context, path string) (*internalapi.Response, error) {
	f.record("DELETE", path)
	return jsonResp(404, nil), nil
}

// ── 1. Validate: happy path ───────────────────────────────────────────────

func TestRecipe_Validate_HappyPath(t *testing.T) {
	doc := &RecipeDocument{
		APIVersion: "crewship/v1",
		Kind:       "Recipe",
		Metadata:   internalapi.Metadata{Name: "Code Review", Slug: "code-review"},
		Spec: RecipeSpec{
			Install: true,
			Inputs:  map[string]any{"crew_slug": "my-crew"},
		},
	}
	ctx := internalapi.WorkspaceContext{
		DeclaredCrews: []internalapi.SlugLookup{{Slug: "my-crew"}},
	}
	if err := doc.Validate(ctx); err != nil {
		t.Fatalf("Validate: %v", err)
	}
}

// ── 2. Validate: error paths ──────────────────────────────────────────────

func TestRecipe_Validate_MissingSlug(t *testing.T) {
	doc := &RecipeDocument{}
	err := doc.Validate(internalapi.WorkspaceContext{})
	if err == nil || !strings.Contains(err.Error(), "metadata.slug is required") {
		t.Fatalf("want slug-required error, got %v", err)
	}
}

func TestRecipe_Validate_CrewSlugWrongType(t *testing.T) {
	doc := &RecipeDocument{
		Metadata: internalapi.Metadata{Slug: "code-review"},
		Spec: RecipeSpec{
			Install: true,
			Inputs:  map[string]any{"crew_slug": 42},
		},
	}
	err := doc.Validate(internalapi.WorkspaceContext{})
	if err == nil || !strings.Contains(err.Error(), "inputs.crew_slug must be a string") {
		t.Fatalf("want crew_slug-type error, got %v", err)
	}
}

func TestRecipe_Validate_UnknownCrew(t *testing.T) {
	doc := &RecipeDocument{
		Metadata: internalapi.Metadata{Slug: "code-review"},
		Spec: RecipeSpec{
			Install: true,
			Inputs:  map[string]any{"crew_slug": "ghost"},
		},
	}
	err := doc.Validate(internalapi.WorkspaceContext{})
	if err == nil || !strings.Contains(err.Error(), `inputs.crew_slug "ghost"`) {
		t.Fatalf("want unknown-crew error, got %v", err)
	}
}

// ── 3. Plan: install=true, remote nil → Create ────────────────────────────

func TestRecipe_Plan_InstallWhenAbsent(t *testing.T) {
	doc := &RecipeDocument{
		Metadata: internalapi.Metadata{Name: "Code Review", Slug: "code-review"},
		Spec: RecipeSpec{
			Install: true,
			Inputs: map[string]any{
				"credential_values": map[string]any{"ANTHROPIC_API_KEY": "sk-test"},
			},
		},
	}
	client := newFakeClient()
	var capturedSlug string
	var capturedBody map[string]any
	client.installCallback = func(slug string, body any) {
		capturedSlug = slug
		if m, ok := body.(map[string]any); ok {
			capturedBody = m
		}
	}

	items, err := doc.Plan(context.Background(), client, nil)
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	if len(items) != 1 {
		t.Fatalf("want 1 item, got %d", len(items))
	}
	if items[0].Action != internalapi.ActionCreate {
		t.Errorf("want ActionCreate, got %s", items[0].Action)
	}
	if items[0].Exec == nil {
		t.Fatal("Create item must have non-nil Exec")
	}
	if err := items[0].Exec(context.Background(), client); err != nil {
		t.Fatalf("Exec: %v", err)
	}
	if capturedSlug != "code-review" {
		t.Errorf("want install slug code-review, got %q", capturedSlug)
	}
	if capturedBody == nil {
		t.Fatal("install body was nil")
	}
	if _, ok := capturedBody["credential_values"]; !ok {
		t.Errorf("install body missing credential_values: %v", capturedBody)
	}
}

// ── 4. Plan: install=true, remote.Installed → Unchanged ───────────────────

func TestRecipe_Plan_InstallWhenAlreadyInstalled(t *testing.T) {
	doc := &RecipeDocument{
		Metadata: internalapi.Metadata{Slug: "code-review"},
		Spec:     RecipeSpec{Install: true},
	}
	remote := &RecipeRemote{Slug: "code-review", Installed: true}

	client := newFakeClient()
	items, err := doc.Plan(context.Background(), client, remote)
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	if len(items) != 1 || items[0].Action != internalapi.ActionUnchanged {
		t.Fatalf("want single Unchanged, got %+v", items)
	}
	if items[0].Exec != nil {
		t.Error("Unchanged items must have nil Exec")
	}
	if !strings.Contains(items[0].Description, "already installed") {
		t.Errorf("want already-installed description, got %q", items[0].Description)
	}
	// No HTTP traffic should fire for an Unchanged plan.
	if len(client.calls) != 0 {
		t.Errorf("Unchanged plan should issue zero requests, got %v", client.calls)
	}
}

// ── 5. Plan: install=false + installed → Unchanged + warning ──────────────

func TestRecipe_Plan_UninstallNotSupported(t *testing.T) {
	doc := &RecipeDocument{
		Metadata: internalapi.Metadata{Slug: "code-review"},
		Spec:     RecipeSpec{Install: false},
	}
	remote := &RecipeRemote{Slug: "code-review", Installed: true}

	client := newFakeClient()
	items, err := doc.Plan(context.Background(), client, remote)
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	if len(items) != 1 {
		t.Fatalf("want 1 item, got %d", len(items))
	}
	if items[0].Action != internalapi.ActionUnchanged {
		t.Errorf("want ActionUnchanged for missing-DELETE path, got %s", items[0].Action)
	}
	if items[0].Exec != nil {
		t.Error("uninstall-not-supported item must have nil Exec")
	}
	if !strings.Contains(items[0].Description, uninstallWarning) {
		t.Errorf("want uninstall warning in description, got %q", items[0].Description)
	}
	if len(client.calls) != 0 {
		t.Errorf("warning plan should issue zero requests, got %v", client.calls)
	}
}

// ── 6. Plan: install=false + not installed → Unchanged (no warning) ───────

func TestRecipe_Plan_UninstallWhenAlreadyAbsent(t *testing.T) {
	doc := &RecipeDocument{
		Metadata: internalapi.Metadata{Slug: "code-review"},
		Spec:     RecipeSpec{Install: false},
	}

	client := newFakeClient()
	items, err := doc.Plan(context.Background(), client, nil)
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	if len(items) != 1 || items[0].Action != internalapi.ActionUnchanged {
		t.Fatalf("want single Unchanged, got %+v", items)
	}
	if strings.Contains(items[0].Description, uninstallWarning) {
		t.Errorf("benign uninstall-no-op should not carry warning, got %q", items[0].Description)
	}
}

// ── 7. LookupRecipeRemote: catalog lookup ─────────────────────────────────

func TestLookupRecipeRemote_Installed(t *testing.T) {
	client := newFakeClient()
	client.recipes["code-review"] = RecipeRemote{
		ID:        "rec_code_review",
		Slug:      "code-review",
		Installed: true,
	}
	doc := &RecipeDocument{Metadata: internalapi.Metadata{Slug: "code-review"}}
	got, err := LookupRecipeRemote(context.Background(), client, doc)
	if err != nil {
		t.Fatalf("LookupRecipeRemote: %v", err)
	}
	if got == nil || !got.Installed || got.Slug != "code-review" {
		t.Fatalf("want installed remote, got %+v", got)
	}
}

func TestLookupRecipeRemote_NotInCatalog(t *testing.T) {
	client := newFakeClient()
	client.catalog404["ghost"] = true
	doc := &RecipeDocument{Metadata: internalapi.Metadata{Slug: "ghost"}}
	got, err := LookupRecipeRemote(context.Background(), client, doc)
	if err != nil {
		t.Fatalf("LookupRecipeRemote: %v", err)
	}
	if got != nil {
		t.Fatalf("want nil for 404, got %+v", got)
	}
}

// ── 8. ExportRecipes: only installed rows round-trip ──────────────────────

func TestExportRecipes_OnlyInstalled(t *testing.T) {
	client := newFakeClient()
	client.recipes["code-review"] = RecipeRemote{
		ID: "rec_a", Slug: "code-review", Installed: true,
	}
	client.recipes["research"] = RecipeRemote{
		ID: "rec_b", Slug: "research", Installed: false,
	}
	client.recipes["analytics"] = RecipeRemote{
		ID: "rec_c", Slug: "analytics", Installed: true,
	}

	docs, err := ExportRecipes(context.Background(), client)
	if err != nil {
		t.Fatalf("ExportRecipes: %v", err)
	}
	if len(docs) != 2 {
		t.Fatalf("want 2 installed docs, got %d", len(docs))
	}
	seen := map[string]bool{}
	for _, d := range docs {
		if d.Kind != "Recipe" {
			t.Errorf("kind = %q, want Recipe", d.Kind)
		}
		if d.APIVersion != "crewship/v1" {
			t.Errorf("apiVersion = %q, want crewship/v1", d.APIVersion)
		}
		if !d.Spec.Install {
			t.Errorf("export should set Install=true, slug=%s", d.Metadata.Slug)
		}
		seen[d.Metadata.Slug] = true
	}
	if !seen["code-review"] || !seen["analytics"] {
		t.Errorf("missing expected slugs in export: %v", seen)
	}
	if seen["research"] {
		t.Error("uninstalled recipe should NOT appear in export")
	}
}
