import { beforeEach, describe, expect, it, vi } from "vitest"
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react"
import { CrewServiceQuotas } from "../crew-service-quotas"
vi.mock("sonner", () => ({ toast: { success: vi.fn() } }))
const legacy = JSON.stringify([{ name: "redis", image: "redis:7", env_refs: ["CACHE_TOKEN"], ports: ["6379"], volumes: [{ name: "data", mount: "/data" }] }])
const enforced = JSON.stringify([{ name: "redis", image: "redis:7", quota_enforced: true, volumes: [{ name: "data", mount: "/data", quota_bytes: 64 * 1024 * 1024, generation: 1 }] }])
describe("service disk policy", () => {
  beforeEach(cleanup)
  it("preserves other declarations and sends the exact snapshot when enabling quotas", async () => {
    const save = vi.fn().mockResolvedValue(undefined)
    render(<CrewServiceQuotas servicesJSON={legacy} canManage save={save} />)
    expect(screen.getByText(/Legacy trusted storage/)).toBeInTheDocument()
    fireEvent.click(screen.getByRole("checkbox", { name: "redis: Enforce disk quotas" }))
    fireEvent.change(screen.getByRole("spinbutton", { name: "redis/data: Capacity in MiB" }), { target: { value: "128" } })
    fireEvent.click(screen.getByRole("button", { name: "Save disk policy" }))
    expect(save).not.toHaveBeenCalled()
    fireEvent.click(screen.getByRole("checkbox", { name: /I understand/ }))
    fireEvent.click(screen.getByRole("button", { name: "Save disk policy" }))
    await waitFor(() => expect(save).toHaveBeenCalledOnce())
    const body = save.mock.calls[0][0]
    expect(body.expected_services_json).toBe(legacy)
    expect(JSON.parse(body.services_json)).toEqual([{ name: "redis", image: "redis:7", env_refs: ["CACHE_TOKEN"], ports: ["6379"], quota_enforced: true, volumes: [{ name: "data", mount: "/data", quota_bytes: 128 * 1024 * 1024, generation: 1 }] }])
    expect(body).not.toHaveProperty("helper_socket")
  })
  it("rejects same-generation resize, invalid capacities and fractional generations", async () => {
    const save = vi.fn()
    render(<CrewServiceQuotas servicesJSON={enforced} canManage save={save} />)
    const capacity = screen.getByRole("spinbutton", { name: "redis/data: Capacity in MiB" })
    fireEvent.change(capacity, { target: { value: "128" } })
    fireEvent.click(screen.getByRole("button", { name: "Save disk policy" }))
    expect(screen.getByRole("alert")).toHaveTextContent("Increase the generation")
    fireEvent.change(capacity, { target: { value: "31" } })
    fireEvent.click(screen.getByRole("button", { name: "Save disk policy" }))
    expect(screen.getByRole("alert")).toHaveTextContent("32–65,536 MiB")
    fireEvent.change(capacity, { target: { value: "128" } })
    fireEvent.change(screen.getByRole("spinbutton", { name: "redis/data: Volume generation" }), { target: { value: "1.5" } })
    fireEvent.click(screen.getByRole("button", { name: "Save disk policy" }))
    expect(save).not.toHaveBeenCalled()
  })
  it("allows a new acknowledged generation and retains the draft after a conflict", async () => {
    const save = vi.fn().mockRejectedValue(new Error("409"))
    render(<CrewServiceQuotas servicesJSON={enforced} canManage save={save} />)
    fireEvent.change(screen.getByRole("spinbutton", { name: "redis/data: Capacity in MiB" }), { target: { value: "128" } })
    fireEvent.change(screen.getByRole("spinbutton", { name: "redis/data: Volume generation" }), { target: { value: "2" } })
    fireEvent.click(screen.getByRole("checkbox", { name: /I understand/ }))
    fireEvent.click(screen.getByRole("button", { name: "Save disk policy" }))
    expect(await screen.findByRole("alert")).toHaveTextContent("Refresh the crew")
    expect(screen.getByRole("spinbutton", { name: "redis/data: Capacity in MiB" })).toHaveValue(128)
    expect(save.mock.calls[0][0].expected_services_json).toBe(enforced)
  })
  it("warns that quota storage makes crew and workspace backups refuse", () => {
    const save = vi.fn()
    const { rerender } = render(<CrewServiceQuotas servicesJSON={legacy} canManage save={save} />)
    expect(screen.queryByText(/backups of this crew and its workspace are refused/)).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole("checkbox", { name: "redis: Enforce disk quotas" }))
    expect(screen.getByRole("checkbox", { name: /I understand/ }).closest("label")).toHaveTextContent(/backups of this crew and its workspace are refused/)
    rerender(<CrewServiceQuotas servicesJSON={enforced} canManage={false} save={save} />)
    expect(screen.getByRole("note")).toHaveTextContent(/backups of this crew and its workspace are refused/)
  })
  it("offers no mutation below manager and does not reconstruct private settings", () => {
    const save = vi.fn()
    const { rerender } = render(<CrewServiceQuotas servicesJSON={enforced} canManage={false} save={save} />)
    expect(screen.queryByRole("checkbox")).not.toBeInTheDocument()
    expect(screen.getByRole("spinbutton", { name: "redis/data: Capacity in MiB" })).toBeDisabled()
    rerender(<CrewServiceQuotas servicesJSON="[service configuration withheld: contains private runtime settings]" canManage save={save} />)
    expect(screen.getByRole("status")).toHaveTextContent("private settings")
    expect(screen.queryByRole("button", { name: "Save disk policy" })).not.toBeInTheDocument()
    expect(save).not.toHaveBeenCalled()
  })
})
