// Package apidocs renders the generated OpenAPI document as browsable HTML,
// served by the instance itself at /openapi alongside the machine-readable
// /openapi.json (#1846).
//
// Why a hand-written renderer instead of Swagger UI / Redoc / RapiDoc: the
// binary embeds its entire frontend and has to keep working offline and
// air-gapped, so any renderer must be vendored, not loaded from a CDN. The
// smallest of those bundles is ~1 MB of minified third-party JavaScript that
// would have to be reviewed, licence-checked and kept current, and all of them
// ship the whole 3 MB spec to the browser to parse it there. Rendering server
// side costs one JSON parse per process, sends the reader only the page they
// asked for, and needs no third-party code at all — which is also what lets
// this surface run under a strict `default-src 'none'` CSP with no
// 'unsafe-inline' and no 'unsafe-eval'.
//
// The document is a route catalog generated by cmd/gen-openapi from the actual
// route registrations, not a hand-authored contract. The rendering says so, in
// the page, because a reader who mistakes it for hand-authored prose will
// misread `required: false` (see docs/api-reference/openapi.mdx and #1824).
package apidocs

import (
	"encoding/json"
	"sort"
	"strings"
)

// methodOrder is the order operations are listed in within a path, chosen to
// read as a lifecycle (fetch, create, replace, amend, remove) rather than
// alphabetically.
var methodOrder = map[string]int{
	"get": 0, "post": 1, "put": 2, "patch": 3, "delete": 4,
	"head": 5, "options": 6, "trace": 7,
}

func isMethod(s string) bool {
	_, ok := methodOrder[s]
	return ok
}

type specDoc struct {
	OpenAPI string `json:"openapi"`
	Info    struct {
		Title       string `json:"title"`
		Version     string `json:"version"`
		Description string `json:"description"`
	} `json:"info"`
	Paths      map[string]map[string]*operation `json:"paths"`
	Components struct {
		Schemas         map[string]*schema         `json:"schemas"`
		SecuritySchemes map[string]*securityScheme `json:"securitySchemes"`
	} `json:"components"`
}

type operation struct {
	OperationID string                `json:"operationId"`
	Summary     string                `json:"summary"`
	Description string                `json:"description"`
	Tags        []string              `json:"tags"`
	Deprecated  bool                  `json:"deprecated"`
	Parameters  []*parameter          `json:"parameters"`
	RequestBody *requestBody          `json:"requestBody"`
	Responses   map[string]*response  `json:"responses"`
	Security    []map[string][]string `json:"security"`
}

type parameter struct {
	Name        string  `json:"name"`
	In          string  `json:"in"`
	Required    bool    `json:"required"`
	Deprecated  bool    `json:"deprecated"`
	Description string  `json:"description"`
	Schema      *schema `json:"schema"`
}

type requestBody struct {
	Description string               `json:"description"`
	Required    bool                 `json:"required"`
	Content     map[string]mediaType `json:"content"`
}

type response struct {
	Description string               `json:"description"`
	Content     map[string]mediaType `json:"content"`
}

type mediaType struct {
	Schema *schema `json:"schema"`
}

type securityScheme struct {
	Type   string `json:"type"`
	Scheme string `json:"scheme"`
	In     string `json:"in"`
	Name   string `json:"name"`
}

type schema struct {
	Ref                  string             `json:"$ref"`
	Type                 string             `json:"type"`
	Format               string             `json:"format"`
	Title                string             `json:"title"`
	Description          string             `json:"description"`
	Nullable             bool               `json:"nullable"`
	Enum                 []any              `json:"enum"`
	Items                *schema            `json:"items"`
	Properties           map[string]*schema `json:"properties"`
	Required             []string           `json:"required"`
	AdditionalProperties json.RawMessage    `json:"additionalProperties"`
	OneOf                []*schema          `json:"oneOf"`
	AnyOf                []*schema          `json:"anyOf"`
	AllOf                []*schema          `json:"allOf"`
}

// refName returns the component name a "#/components/schemas/X" pointer names,
// or "" for a pointer this renderer cannot resolve. An unresolvable pointer is
// reported in the page rather than silently dropped — a dangling $ref is a bug
// in the spec, and hiding it is exactly the kind of papering-over that made
// the document untrustworthy before #1819/#1830/#1832.
const schemaRefPrefix = "#/components/schemas/"

func refName(ref string) string {
	if !strings.HasPrefix(ref, schemaRefPrefix) {
		return ""
	}
	return strings.TrimPrefix(ref, schemaRefPrefix)
}

// opEntry is one rendered operation: the spec's operation plus everything the
// pages need that the spec only implies.
type opEntry struct {
	ID         string
	Method     string // upper case, for display
	Path       string
	Tags       []string
	Public     bool // security: [] — answers without credentials
	Deprecated bool
	// Summary and Description are empty for every operation in the current
	// generated document — it carries no prose at all. Rendered when present
	// so that adding prose to the generator shows up here without a change.
	Summary     string
	Description string
	Op          *operation
	// Search is the lower-cased haystack the client-side filter matches on.
	Search string
}

type tagGroup struct {
	Name string
	Ops  []*opEntry
}

type schemaEntry struct {
	Name   string
	Schema *schema
	// UsedBy are the operations whose own parameters, request body or
	// responses name this schema directly.
	UsedBy []*opEntry
	// Reachable reports whether any operation reaches this schema, directly
	// or through another schema.
	Reachable bool
}

// index is the parsed spec plus the derived views the pages render from. Built
// once per process; the spec is embedded in the binary and cannot change under
// a running server.
type index struct {
	doc      *specDoc
	ops      []*opEntry
	opByID   map[string]*opEntry
	tags     []tagGroup
	schemas  []*schemaEntry
	schemaBy map[string]*schemaEntry

	PublicOps          int
	UnreachableSchemas int
}

func newIndex(raw []byte) (*index, error) {
	var d specDoc
	if err := json.Unmarshal(raw, &d); err != nil {
		return nil, err
	}

	ix := &index{
		doc:      &d,
		opByID:   map[string]*opEntry{},
		schemaBy: map[string]*schemaEntry{},
	}

	for p, item := range d.Paths {
		for m, op := range item {
			if !isMethod(m) || op == nil {
				continue
			}
			tags := append([]string(nil), op.Tags...)
			if len(tags) == 0 {
				tags = []string{"untagged"}
			}
			sort.Strings(tags)
			e := &opEntry{
				ID:          op.OperationID,
				Method:      strings.ToUpper(m),
				Path:        p,
				Tags:        tags,
				Public:      len(op.Security) == 0,
				Deprecated:  op.Deprecated,
				Summary:     op.Summary,
				Description: op.Description,
				Op:          op,
			}
			if e.ID == "" {
				e.ID = strings.ToLower(m) + "_" + strings.NewReplacer("/", "_", "{", "", "}", "").Replace(strings.TrimPrefix(p, "/"))
			}
			e.Search = strings.ToLower(strings.Join([]string{e.Method, p, e.ID, strings.Join(tags, " ")}, " "))
			ix.ops = append(ix.ops, e)
			if e.Public {
				ix.PublicOps++
			}
		}
	}
	sort.Slice(ix.ops, func(i, j int) bool {
		a, b := ix.ops[i], ix.ops[j]
		if a.Path != b.Path {
			return a.Path < b.Path
		}
		return methodOrder[strings.ToLower(a.Method)] < methodOrder[strings.ToLower(b.Method)]
	})
	for _, e := range ix.ops {
		// A duplicate operationId means two operations would share a URL on
		// this surface; first one wins and the collision is visible in the
		// index (both rows link to the same page), which is better than
		// pretending the id is unique.
		if _, dup := ix.opByID[e.ID]; !dup {
			ix.opByID[e.ID] = e
		}
	}

	byTag := map[string][]*opEntry{}
	for _, e := range ix.ops {
		for _, t := range e.Tags {
			byTag[t] = append(byTag[t], e)
		}
	}
	names := make([]string, 0, len(byTag))
	for t := range byTag {
		names = append(names, t)
	}
	sort.Strings(names)
	for _, t := range names {
		ix.tags = append(ix.tags, tagGroup{Name: t, Ops: byTag[t]})
	}

	ix.buildSchemaIndex()
	return ix, nil
}

// buildSchemaIndex records which operations name each component schema and
// which schemas no operation can reach at all.
func (ix *index) buildSchemaIndex() {
	names := make([]string, 0, len(ix.doc.Components.Schemas))
	for n := range ix.doc.Components.Schemas {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		e := &schemaEntry{Name: n, Schema: ix.doc.Components.Schemas[n]}
		ix.schemas = append(ix.schemas, e)
		ix.schemaBy[n] = e
	}

	// Direct references: the schemas an operation writes itself.
	frontier := map[string]bool{}
	for _, op := range ix.ops {
		for _, n := range ix.directRefs(op.Op) {
			if e, ok := ix.schemaBy[n]; ok {
				e.UsedBy = append(e.UsedBy, op)
			}
			frontier[n] = true
		}
	}

	// Reachability: follow schema-to-schema references from there.
	seen := map[string]bool{}
	var queue []string
	for n := range frontier {
		queue = append(queue, n)
	}
	for len(queue) > 0 {
		n := queue[0]
		queue = queue[1:]
		if seen[n] {
			continue
		}
		seen[n] = true
		e, ok := ix.schemaBy[n]
		if !ok {
			continue
		}
		e.Reachable = true
		for _, next := range collectRefs(e.Schema, nil) {
			if !seen[next] {
				queue = append(queue, next)
			}
		}
	}
	for _, e := range ix.schemas {
		if !e.Reachable {
			ix.UnreachableSchemas++
		}
	}
}

// directRefs lists the component schemas an operation names in its own
// parameters, request body and responses (without descending into components).
func (ix *index) directRefs(op *operation) []string {
	if op == nil {
		return nil
	}
	var out []string
	for _, p := range op.Parameters {
		if p != nil {
			out = collectRefs(p.Schema, out)
		}
	}
	if op.RequestBody != nil {
		for _, mt := range op.RequestBody.Content {
			out = collectRefs(mt.Schema, out)
		}
	}
	for _, r := range op.Responses {
		if r == nil {
			continue
		}
		for _, mt := range r.Content {
			out = collectRefs(mt.Schema, out)
		}
	}
	return dedupe(out)
}

// collectRefs appends every component-schema name reachable inside s without
// following the references themselves.
func collectRefs(s *schema, out []string) []string {
	if s == nil {
		return out
	}
	if n := refName(s.Ref); n != "" {
		return append(out, n)
	}
	out = collectRefs(s.Items, out)
	for _, p := range s.Properties {
		out = collectRefs(p, out)
	}
	for _, group := range [][]*schema{s.OneOf, s.AnyOf, s.AllOf} {
		for _, sub := range group {
			out = collectRefs(sub, out)
		}
	}
	if len(s.AdditionalProperties) > 0 {
		var sub schema
		if err := json.Unmarshal(s.AdditionalProperties, &sub); err == nil {
			out = collectRefs(&sub, out)
		}
	}
	return out
}

func dedupe(in []string) []string {
	seen := map[string]bool{}
	out := in[:0]
	for _, s := range in {
		if !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	return out
}
