package api

// Persisted agent avatars (#1297) — store / serve / clear the rendered SVG.
//
// Why this exists: an agent's avatar is generated by DiceBear from
// (avatar_seed, avatar_style) on the client, on every render. That makes
// the face a function of the installed library version, so a dependency
// bump silently repaints the whole roster — the 9→10 spike recorded in
// lib/__tests__/agent-avatar-stability.test.ts produced zero identical
// outputs across 10 styles × 5 seeds. Persisting the render freezes each
// agent's face at the version that drew it.
//
// The generator is JS-only, so the server never draws an avatar: the
// client posts the SVG it just rendered (at creation, or lazily the first
// time an editor views an agent that has none). Everything below exists to
// make accepting that client-supplied markup safe.
//
// Threat model. Agent avatars are already SVG today, inlined as data URIs
// into <img>, which never executes script — so the render path adds no new
// exposure. Serving the same bytes from our own origin does add one: a
// direct navigation to the serve URL renders the document, where SVG
// script would run. Two independent controls close that:
//
//   1. validateAgentAvatarSVG — an allowlist over the tag/attribute
//      vocabulary the generator actually emits (verified by scanning all
//      ten collections). That vocabulary contains no element or attribute
//      capable of loading or executing anything: no <script>, no
//      <foreignObject>, no <use>/<image>, no href of any kind, no event
//      handlers. Anything outside it is refused, so the allowlist is a
//      complete barrier rather than a blocklist that has to anticipate
//      every vector.
//   2. ServeAvatar's `Content-Security-Policy: default-src 'none'; sandbox`
//      plus nosniff, which neutralises active content even if something
//      slipped past (1).

import (
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"regexp"
	"strings"
	"time"
)

// maxAgentAvatarBytes caps a stored avatar. The largest style measured
// across all ten collections (notionists) lands around 20 KB, so 64 KiB is
// generous headroom while keeping the row — and the buffered read — bounded.
const maxAgentAvatarBytes = 64 << 10

// agentAvatarAllowedTags is the element allowlist. It covers the vocabulary
// the DiceBear collections emit plus the handful of neighbouring inert shape
// and gradient elements, so a future minor version that starts using, say,
// <polygon> does not spuriously fail validation. Every entry is a pure
// drawing or metadata element — nothing here can fetch or execute.
//
// Deliberately absent: script, foreignObject, iframe, embed, object, a,
// use, image, animate/set/handler. Those are the ones that turn a picture
// into a program.
var agentAvatarAllowedTags = map[string]bool{
	"svg": true, "g": true, "defs": true, "mask": true, "clippath": true,
	"path": true, "rect": true, "circle": true, "ellipse": true,
	"line": true, "polygon": true, "polyline": true,
	"lineargradient": true, "radialgradient": true, "stop": true,
	"title": true, "desc": true, "metadata": true,
	// RDF/Dublin Core licensing block emitted by the collections.
	"rdf:rdf": true, "rdf:description": true,
	"dc:creator": true, "dc:rights": true, "dc:source": true, "dc:title": true,
	"dcterms:license": true,
}

// agentAvatarAllowedAttrs is the attribute allowlist. Same principle: only
// presentation, geometry and namespace declarations. No href/xlink:href, no
// on* handlers — both are excluded simply by not appearing here.
var agentAvatarAllowedAttrs = map[string]bool{
	"id": true, "class": true, "style": true, "transform": true,
	"width": true, "height": true, "viewbox": true, "version": true,
	"preserveaspectratio": true, "shape-rendering": true,
	"x": true, "y": true, "x1": true, "x2": true, "y1": true, "y2": true,
	"cx": true, "cy": true, "r": true, "rx": true, "ry": true,
	"d": true, "points": true, "offset": true, "opacity": true,
	"fill": true, "fill-opacity": true, "fill-rule": true, "clip-rule": true,
	"clip-path": true, "mask": true, "maskunits": true, "maskcontentunits": true,
	"stroke": true, "stroke-width": true, "stroke-opacity": true,
	"stroke-linecap": true, "stroke-linejoin": true, "stroke-miterlimit": true,
	"stroke-dasharray": true, "stroke-dashoffset": true,
	"gradientunits": true, "gradienttransform": true, "spreadmethod": true,
	"stop-color": true, "stop-opacity": true,
	"xmlns": true, "xmlns:dc": true, "xmlns:dcterms": true,
	"xmlns:rdf": true, "xmlns:xsi": true, "xsi:type": true,
	"rdf:about": true, "rdf:resource": true,
}

var (
	// Matches an element tag and captures its name: `<rect ...>`, `</g>`.
	agentAvatarTagRe = regexp.MustCompile(`<\s*/?\s*([A-Za-z_][\w:.\-]*)`)
	// Matches an attribute name inside a tag body.
	agentAvatarAttrRe = regexp.MustCompile(`([A-Za-z_][\w:.\-]*)\s*=`)
	// url(...) references must stay internal — url(#gradient) is how fill
	// and mask point at <defs>. Anything else is an outbound fetch.
	agentAvatarURLRe = regexp.MustCompile(`(?i)url\(\s*['"]?\s*([^)'"\s]*)`)
)

// validateAgentAvatarSVG accepts only inert, self-contained SVG. See the
// package comment above for why this is an allowlist rather than a
// blocklist. Returns a caller-facing error describing the first violation.
func validateAgentAvatarSVG(svg string) error {
	trimmed := strings.TrimSpace(svg)
	if trimmed == "" {
		return fmt.Errorf("avatar svg is empty")
	}
	if len(svg) > maxAgentAvatarBytes {
		return fmt.Errorf("avatar svg exceeds %d bytes", maxAgentAvatarBytes)
	}
	if !strings.HasPrefix(trimmed, "<svg") {
		return fmt.Errorf("avatar svg must start with an <svg> root element")
	}
	// Anchoring the tail closes the "valid avatar with a payload appended"
	// shape, where a well-formed <svg>…</svg> is followed by other markup.
	if !strings.HasSuffix(trimmed, "</svg>") {
		return fmt.Errorf("avatar svg must end with </svg>")
	}
	// Comments, CDATA sections, DOCTYPEs and processing instructions can
	// carry markup the tag scanner below would step over. None of them
	// appear in generator output, so refuse them outright rather than
	// trying to parse around them.
	for _, bad := range []string{"<!--", "<![CDATA[", "<!DOCTYPE", "<?"} {
		if strings.Contains(strings.ToUpper(trimmed), strings.ToUpper(bad)) {
			return fmt.Errorf("avatar svg must not contain %q", bad)
		}
	}

	for _, m := range agentAvatarTagRe.FindAllStringSubmatch(trimmed, -1) {
		name := strings.ToLower(m[1])
		if !agentAvatarAllowedTags[name] {
			return fmt.Errorf("avatar svg contains disallowed element <%s>", name)
		}
	}

	// Attribute names are only meaningful inside a tag body, so walk the
	// `<...>` spans rather than the whole document (text content legitimately
	// contains `=` — e.g. a licence URL in the metadata block).
	for _, span := range splitAgentAvatarTagBodies(trimmed) {
		for _, m := range agentAvatarAttrRe.FindAllStringSubmatch(span, -1) {
			name := strings.ToLower(m[1])
			if !agentAvatarAllowedAttrs[name] {
				return fmt.Errorf("avatar svg contains disallowed attribute %q", name)
			}
		}
	}

	for _, m := range agentAvatarURLRe.FindAllStringSubmatch(trimmed, -1) {
		if !strings.HasPrefix(m[1], "#") {
			return fmt.Errorf("avatar svg references an external url(%s)", m[1])
		}
	}
	// Belt and braces: these cannot survive the allowlists above, but a
	// literal match is cheap and makes the intent unmissable to a reader.
	lower := strings.ToLower(trimmed)
	for _, scheme := range []string{"javascript:", "data:text/html", "vbscript:"} {
		if strings.Contains(lower, scheme) {
			return fmt.Errorf("avatar svg contains a %q reference", scheme)
		}
	}
	return nil
}

// splitAgentAvatarTagBodies returns the interior of each `<...>` span, i.e.
// the regions where attributes may legally appear.
func splitAgentAvatarTagBodies(s string) []string {
	var out []string
	for i := 0; i < len(s); {
		open := strings.IndexByte(s[i:], '<')
		if open < 0 {
			break
		}
		open += i
		close := strings.IndexByte(s[open:], '>')
		if close < 0 {
			// Unterminated tag — hand the remainder over so the attribute
			// scan still sees it rather than silently skipping it.
			out = append(out, s[open:])
			break
		}
		close += open
		out = append(out, s[open:close])
		i = close + 1
	}
	return out
}

// agentAvatarHash is the content hash used as the ?v= cache buster. Short
// prefix: it only has to change when the bytes change, not resist collision
// attacks — and it is stored per row so list queries never touch the blob.
func agentAvatarHash(svg string) string {
	sum := sha256.Sum256([]byte(svg))
	return hex.EncodeToString(sum[:])[:16]
}

// agentAvatarURL builds the serve URL for a stored avatar. Returns nil when
// the agent has no stored render, which is the signal for the client to fall
// back to generating from (avatar_seed, avatar_style).
func agentAvatarURL(agentID, hash string) *string {
	if hash == "" {
		return nil
	}
	u := fmt.Sprintf("/api/v1/agents/%s/avatar?v=%s", agentID, hash)
	return &u
}

// PutAvatar stores the client-rendered avatar for an agent.
// PUT /api/v1/agents/{agentId}/avatar — body {"svg": "<svg …>"}.
//
// Write-once: it fills an empty slot and refuses to replace a populated one
// with 409. Replacing means DELETE first. Without that rule this endpoint
// would be a standing "swap any teammate's agent portrait" primitive that
// fires on an ordinary page view, since the lazy backfill calls it
// automatically.
func (h *AgentHandler) PutAvatar(w http.ResponseWriter, r *http.Request) {
	agentID := r.PathValue("agentId")
	workspaceID := WorkspaceIDFromContext(r.Context())
	role := RoleFromContext(r.Context())
	user := UserFromContext(r.Context())
	callerUserID := ""
	if user != nil {
		callerUserID = user.ID
	}

	// Same gate as Update: this writes a user-visible attribute of the
	// agent, so it takes the same per-agent edit rights.
	ok, err := canEditAgent(r.Context(), h.db, callerUserID, role, agentID)
	if err != nil {
		replyInternalError(w, h.logger, "agent avatar edit gate", err)
		return
	}
	if !ok {
		replyForbidden(w, h.logger, callerUserID, role, "agent.avatar.put", "agent:"+agentID)
		return
	}

	// Bound the read before decoding: the cap is on the SVG, and the JSON
	// envelope adds only a few bytes of overhead beyond escaping.
	r.Body = http.MaxBytesReader(w, r.Body, maxAgentAvatarBytes*2)
	raw, err := io.ReadAll(r.Body)
	if err != nil {
		replyError(w, http.StatusBadRequest, "avatar payload too large")
		return
	}
	var body struct {
		SVG string `json:"svg"`
	}
	if err := json.Unmarshal(raw, &body); err != nil {
		replyError(w, http.StatusBadRequest, "Invalid JSON body")
		return
	}
	if err := validateAgentAvatarSVG(body.SVG); err != nil {
		replyError(w, http.StatusBadRequest, err.Error())
		return
	}

	hash := agentAvatarHash(body.SVG)
	now := time.Now().UTC().Format(time.RFC3339)
	res, err := h.db.ExecContext(r.Context(), `
		UPDATE agents SET avatar_svg = ?, avatar_svg_hash = ?, updated_at = ?
		WHERE id = ? AND workspace_id = ? AND deleted_at IS NULL AND avatar_svg IS NULL`,
		body.SVG, hash, now, agentID, workspaceID)
	if err != nil {
		replyInternalError(w, h.logger, "store agent avatar", err)
		return
	}
	if affected, _ := res.RowsAffected(); affected == 0 {
		// Zero rows means either the agent isn't there or the slot is
		// already filled — distinguish so a backfill race reads as the
		// benign conflict it is rather than a missing agent.
		found, ferr := agentExists(r.Context(), h.db, agentID, workspaceID)
		if ferr != nil {
			replyInternalError(w, h.logger, "agent avatar existence check", ferr)
			return
		}
		if !found {
			replyError(w, http.StatusNotFound, "Agent not found")
			return
		}
		replyError(w, http.StatusConflict, "Agent already has a stored avatar; clear it first")
		return
	}

	writeJSON(w, http.StatusOK, map[string]any{"avatar_url": *agentAvatarURL(agentID, hash)})
}

// ServeAvatar streams an agent's stored avatar SVG.
// GET /api/v1/agents/{agentId}/avatar — authed; any workspace member may
// fetch it, since rosters render each other. The ?v= query is ignored (it
// exists purely to bust the browser cache when the bytes change).
func (h *AgentHandler) ServeAvatar(w http.ResponseWriter, r *http.Request) {
	agentID := r.PathValue("agentId")
	workspaceID := WorkspaceIDFromContext(r.Context())

	var svg sql.NullString
	err := h.db.QueryRowContext(r.Context(),
		`SELECT avatar_svg FROM agents WHERE id = ? AND workspace_id = ? AND deleted_at IS NULL`,
		agentID, workspaceID).Scan(&svg)
	if err == sql.ErrNoRows || (err == nil && !svg.Valid) {
		// No stored render is not an error condition — the client just
		// generates from the seed, exactly as it did before this feature.
		replyError(w, http.StatusNotFound, "avatar not found")
		return
	}
	if err != nil {
		replyInternalError(w, h.logger, "read agent avatar", err)
		return
	}

	w.Header().Set("Content-Type", "image/svg+xml")
	w.Header().Set("X-Content-Type-Options", "nosniff")
	// This is the control that makes serving SVG from our own origin safe
	// on direct navigation: no subresource may load and the document is
	// sandboxed into a unique opaque origin, so any active content that
	// got past validateAgentAvatarSVG still cannot reach anything.
	w.Header().Set("Content-Security-Policy", "default-src 'none'; sandbox")
	// Immutable is honest here: the URL carries a content hash, so these
	// bytes never change for this URL. A re-render lands on a new ?v=.
	w.Header().Set("Cache-Control", "private, max-age=31536000, immutable")
	w.WriteHeader(http.StatusOK)
	_, _ = io.WriteString(w, svg.String)
}

// DeleteAvatar drops the stored render, returning the agent to
// generate-from-seed. Also the way to replace an avatar, given PutAvatar's
// write-once rule.
// DELETE /api/v1/agents/{agentId}/avatar
func (h *AgentHandler) DeleteAvatar(w http.ResponseWriter, r *http.Request) {
	agentID := r.PathValue("agentId")
	workspaceID := WorkspaceIDFromContext(r.Context())
	role := RoleFromContext(r.Context())
	user := UserFromContext(r.Context())
	callerUserID := ""
	if user != nil {
		callerUserID = user.ID
	}

	ok, err := canEditAgent(r.Context(), h.db, callerUserID, role, agentID)
	if err != nil {
		replyInternalError(w, h.logger, "agent avatar edit gate", err)
		return
	}
	if !ok {
		replyForbidden(w, h.logger, callerUserID, role, "agent.avatar.delete", "agent:"+agentID)
		return
	}

	now := time.Now().UTC().Format(time.RFC3339)
	if _, err := h.db.ExecContext(r.Context(), `
		UPDATE agents SET avatar_svg = NULL, avatar_svg_hash = NULL, updated_at = ?
		WHERE id = ? AND workspace_id = ? AND deleted_at IS NULL`,
		now, agentID, workspaceID); err != nil {
		replyInternalError(w, h.logger, "clear agent avatar", err)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}
