package api

// Persisted agent avatars (#1297) — store / serve / clear the rendered SVG.
//
// Why this exists: an agent's avatar is generated by DiceBear from
// (avatar_seed, avatar_style) on the client, on every render. That makes
// the face a function of the installed library version, so a dependency
// bump silently repaints the whole roster — the 9→10 spike recorded in
// lib/__tests__/agent-avatar-stability.test.ts produced zero identical
// outputs across 10 styles × 5 seeds. Persisting the render freezes each
// agent's face at the version that drew it.
//
// The generator is JS-only, so the server never draws an avatar: the
// client posts the SVG it just rendered (at creation, or lazily the first
// time an editor views an agent that has none). Everything below exists to
// make accepting that client-supplied markup safe.
//
// Threat model. Agent avatars are already SVG today, inlined as data URIs
// into <img>, which never executes script — so the render path adds no new
// exposure. Serving the same bytes from our own origin does add one: a
// direct navigation to the serve URL renders the document, where SVG
// script would run. Two independent controls close that:
//
//   1. validateAgentAvatarSVG — an allowlist over the tag/attribute
//      vocabulary the generator actually emits (verified by scanning all
//      ten collections). That vocabulary contains no element or attribute
//      capable of loading or executing anything: no <script>, no
//      <foreignObject>, no <use>/<image>, no href of any kind, no event
//      handlers. Anything outside it is refused.
//
//      The allowlist is only as good as the thing applying it. The first
//      version scanned with regexes and was bypassable — '>' is legal
//      inside an XML attribute value, so `width=">" onload="…"` hid the
//      handler in a region the scanner never examined. It now walks a real
//      encoding/xml token stream. See
//      TestValidateAgentAvatarSVG_ScannerBypassesStayClosed; that is a
//      standing argument against ever "simplifying" this back to pattern
//      matching.
//   2. ServeAvatar's `Content-Security-Policy: default-src 'none'; sandbox`
//      plus nosniff, which neutralises active content even if something
//      slipped past (1). These are two controls precisely because (1) has
//      been wrong once already — neither is treated as sufficient alone.

import (
	"context"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"encoding/json"
	"encoding/xml"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

// maxAgentAvatarBytes caps a stored avatar. The largest style measured
// across all ten collections (notionists) lands around 20 KB, so 64 KiB is
// generous headroom while keeping the row — and the buffered read — bounded.
const maxAgentAvatarBytes = 64 << 10

// agentAvatarAllowedTags is the element allowlist, keyed by LOCAL name
// (namespace prefix stripped, lowercased). It covers the vocabulary the
// DiceBear collections emit plus the handful of neighbouring inert shape and
// gradient elements, so a future minor version that starts using, say,
// <polygon> does not spuriously fail validation. Every entry is a pure
// drawing or metadata element — nothing here can fetch or execute.
//
// Deliberately absent: script, foreignObject, iframe, embed, object, a,
// use, image, animate/set/handler. Those are the ones that turn a picture
// into a program. Matching on the local name means a foreign-namespace
// dodge (<x:script>) is refused too.
var agentAvatarAllowedTags = map[string]bool{
	"svg": true, "g": true, "defs": true, "mask": true, "clippath": true,
	"path": true, "rect": true, "circle": true, "ellipse": true,
	"line": true, "polygon": true, "polyline": true,
	"lineargradient": true, "radialgradient": true, "stop": true,
	"title": true, "desc": true, "metadata": true,
	// RDF/Dublin Core licensing block emitted by the collections. Local
	// names only: rdf:RDF -> "rdf", dc:creator -> "creator", and so on.
	"rdf": true, "description": true,
	"creator": true, "rights": true, "source": true, "license": true,
}

// agentAvatarAllowedAttrs is the attribute allowlist, also keyed by local
// name. Same principle: only presentation, geometry and metadata. No
// href/xlink:href, no on* handlers — both are excluded simply by not
// appearing here, in any namespace.
var agentAvatarAllowedAttrs = map[string]bool{
	"id": true, "class": true, "style": true, "transform": true,
	"width": true, "height": true, "viewbox": true, "version": true,
	"preserveaspectratio": true, "shape-rendering": true,
	"x": true, "y": true, "x1": true, "x2": true, "y1": true, "y2": true,
	"cx": true, "cy": true, "r": true, "rx": true, "ry": true,
	"d": true, "points": true, "offset": true, "opacity": true,
	"fill": true, "fill-opacity": true, "fill-rule": true, "clip-rule": true,
	"clip-path": true, "mask": true, "maskunits": true, "maskcontentunits": true,
	"stroke": true, "stroke-width": true, "stroke-opacity": true,
	"stroke-linecap": true, "stroke-linejoin": true, "stroke-miterlimit": true,
	"stroke-dasharray": true, "stroke-dashoffset": true,
	"gradientunits": true, "gradienttransform": true, "spreadmethod": true,
	"stop-color": true, "stop-opacity": true,
	// Metadata-block attributes: xsi:type, rdf:about, rdf:resource.
	"type": true, "about": true, "resource": true,
}

// validateAgentAvatarSVG accepts only inert, self-contained SVG. See the
// package comment above for why this is an allowlist rather than a
// blocklist. Returns a caller-facing error describing the first violation.
//
// This walks a real XML token stream rather than scanning with regexes. An
// earlier hand-rolled scanner split tags on the first '>' — but '>' is legal
// inside an XML attribute value, so `<rect d="a>b" onload="alert(1)"/>`
// parked the handler in a region the scanner never looked at, and it was
// accepted. Regexes cannot decide XML; the parser can. Parsing also decodes
// entity references before the value checks below see them, which closes the
// matching `fill="&#x6a;avascript:..."` dodge.
func validateAgentAvatarSVG(svg string) error {
	trimmed := strings.TrimSpace(svg)
	if trimmed == "" {
		return fmt.Errorf("avatar svg is empty")
	}
	if len(svg) > maxAgentAvatarBytes {
		return fmt.Errorf("avatar svg exceeds %d bytes", maxAgentAvatarBytes)
	}

	dec := xml.NewDecoder(strings.NewReader(trimmed))
	// Leave dec.Entity nil: only the five predefined XML entities and numeric
	// character references resolve. An undefined named entity is a parse
	// error rather than something we have to reason about, and generator
	// output never uses one.
	dec.Strict = true

	depth := 0
	sawRoot := false
	for {
		tok, err := dec.Token()
		if err == io.EOF {
			break
		}
		if err != nil {
			return fmt.Errorf("avatar svg is not well-formed XML: %w", err)
		}

		switch t := tok.(type) {
		case xml.StartElement:
			// Trailing junk after the root element closes — the "valid
			// avatar with a payload appended" shape.
			if sawRoot && depth == 0 {
				return fmt.Errorf("avatar svg must contain a single <svg> root element")
			}
			if depth == 0 {
				if strings.ToLower(t.Name.Local) != "svg" {
					return fmt.Errorf("avatar svg root element must be <svg>, got <%s>", t.Name.Local)
				}
				sawRoot = true
			}
			name := strings.ToLower(t.Name.Local)
			if !agentAvatarAllowedTags[name] {
				return fmt.Errorf("avatar svg contains disallowed element <%s>", name)
			}
			for _, attr := range t.Attr {
				if err := checkAgentAvatarAttr(attr); err != nil {
					return err
				}
			}
			depth++
		case xml.EndElement:
			depth--
		case xml.ProcInst:
			// A leading `<?xml version="1.0"?>` is inert boilerplate that
			// every SVG editor writes, and `crewship agent avatar set` takes
			// a file from the user — rejecting it would be a confusing
			// papercut on a documented path. Every OTHER processing
			// instruction is refused: `<?xml-stylesheet?>` in particular can
			// pull in an external stylesheet.
			if strings.ToLower(t.Target) != "xml" || sawRoot {
				return fmt.Errorf("avatar svg must not contain processing instructions")
			}
		case xml.Directive:
			// DOCTYPE and friends — entity-definition territory.
			return fmt.Errorf("avatar svg must not contain XML directives")
		case xml.Comment:
			return fmt.Errorf("avatar svg must not contain comments")
		case xml.CharData:
			// Text is inert; it only becomes markup if something above let a
			// dangerous element through, and nothing does.
			_ = t
		}
	}
	if !sawRoot {
		return fmt.Errorf("avatar svg must contain an <svg> root element")
	}
	if depth != 0 {
		return fmt.Errorf("avatar svg has unbalanced elements")
	}
	return nil
}

// checkAgentAvatarAttr validates one parsed attribute: its name against the
// allowlist, and its (entity-decoded) value against the reference rules.
func checkAgentAvatarAttr(attr xml.Attr) error {
	// Namespace declarations. encoding/xml surfaces `xmlns="…"` as local
	// name "xmlns", and `xmlns:dc="…"` as space "xmlns", local "dc". Both are
	// inert bookkeeping and carry the http:// URIs that would otherwise trip
	// the external-reference check below.
	if attr.Name.Space == "xmlns" || strings.ToLower(attr.Name.Local) == "xmlns" {
		return nil
	}

	name := strings.ToLower(attr.Name.Local)
	if !agentAvatarAllowedAttrs[name] {
		return fmt.Errorf("avatar svg contains disallowed attribute %q", name)
	}

	// url(...) must stay internal — url(#gradient) is how fill and mask point
	// at <defs>. Anything else is an outbound fetch.
	value := attr.Value
	lower := strings.ToLower(value)
	for idx := strings.Index(lower, "url("); idx >= 0; {
		rest := strings.TrimLeft(value[idx+len("url("):], " \t\r\n'\"")
		if !strings.HasPrefix(rest, "#") {
			target, _, _ := strings.Cut(rest, ")")
			return fmt.Errorf("avatar svg references an external url(%s)", strings.TrimSpace(target))
		}
		next := strings.Index(lower[idx+1:], "url(")
		if next < 0 {
			break
		}
		idx += 1 + next
	}
	for _, scheme := range []string{"javascript:", "vbscript:", "data:text/html"} {
		if strings.Contains(lower, scheme) {
			return fmt.Errorf("avatar svg contains a %q reference", scheme)
		}
	}
	return nil
}

// agentAvatarHash is the content hash used as the ?v= cache buster. Short
// prefix: it only has to change when the bytes change, not resist collision
// attacks — and it is stored per row so list queries never touch the blob.
func agentAvatarHash(svg string) string {
	sum := sha256.Sum256([]byte(svg))
	return hex.EncodeToString(sum[:])[:16]
}

// agentAvatarURL builds the serve URL for a stored avatar. Returns nil when
// the agent has no stored render, which is the signal for the client to fall
// back to generating from (avatar_seed, avatar_style).
//
// workspace_id is part of the URL because the GET route is registered behind
// wsCtx, which resolves the workspace from the query string, a {workspaceId}
// path segment, or the X-Workspace-ID header. This path has no workspace
// segment and an <img> tag cannot set a header, so without the query param
// every stored avatar 400s at the middleware — the client then falls back to
// generating one and the whole feature silently does nothing.
//
// Dropping wsCtx from the route would also make the URL fetchable and is the
// wrong fix: ServeAvatar uses the workspace as its tenant scope, so the gate
// is what keeps one workspace's avatars out of another's reach.
func agentAvatarURL(agentID, hash, workspaceID string) *string {
	// No workspace means no fetchable URL. Returning one anyway would hand
	// the client a link that 400s; nil routes it to the seed fallback, which
	// is the documented behaviour for "no stored render available".
	if hash == "" || workspaceID == "" || agentID == "" {
		return nil
	}
	u := fmt.Sprintf("/api/v1/agents/%s/avatar?v=%s&workspace_id=%s",
		url.PathEscape(agentID), url.QueryEscape(hash), url.QueryEscape(workspaceID))
	return &u
}

// PutAvatar stores the client-rendered avatar for an agent.
// PUT /api/v1/agents/{agentId}/avatar — body {"svg": "<svg …>"}.
//
// Write-once: it fills an empty slot and refuses to replace a populated one
// with 409. Replacing means DELETE first. Without that rule this endpoint
// would be a standing "swap any teammate's agent portrait" primitive that
// fires on an ordinary page view, since the lazy backfill calls it
// automatically.
func (h *AgentHandler) PutAvatar(w http.ResponseWriter, r *http.Request) {
	agentID := r.PathValue("agentId")
	workspaceID := WorkspaceIDFromContext(r.Context())
	role := RoleFromContext(r.Context())
	user := UserFromContext(r.Context())
	callerUserID := ""
	if user != nil {
		callerUserID = user.ID
	}

	// Same gate as Update: this writes a user-visible attribute of the
	// agent, so it takes the same per-agent edit rights.
	ok, err := canEditAgent(r.Context(), h.db, callerUserID, role, agentID)
	if err != nil {
		replyInternalError(w, h.logger, "agent avatar edit gate", err)
		return
	}
	if !ok {
		replyForbidden(w, h.logger, callerUserID, role, "agent.avatar.put", "agent:"+agentID)
		return
	}

	// Bound the read before decoding: the cap is on the SVG, and the JSON
	// envelope adds only a few bytes of overhead beyond escaping.
	r.Body = http.MaxBytesReader(w, r.Body, maxAgentAvatarBytes*2)
	raw, err := io.ReadAll(r.Body)
	if err != nil {
		replyError(w, http.StatusBadRequest, "avatar payload too large")
		return
	}
	var body struct {
		SVG string `json:"svg"`
	}
	if err := json.Unmarshal(raw, &body); err != nil {
		replyError(w, http.StatusBadRequest, "Invalid JSON body")
		return
	}
	if err := validateAgentAvatarSVG(body.SVG); err != nil {
		replyError(w, http.StatusBadRequest, err.Error())
		return
	}

	hash := agentAvatarHash(body.SVG)
	now := time.Now().UTC().Format(time.RFC3339)
	res, err := h.db.ExecContext(r.Context(), `
		UPDATE agents SET avatar_svg = ?, avatar_svg_hash = ?, updated_at = ?
		WHERE id = ? AND workspace_id = ? AND deleted_at IS NULL AND avatar_svg IS NULL`,
		body.SVG, hash, now, agentID, workspaceID)
	if err != nil {
		replyInternalError(w, h.logger, "store agent avatar", err)
		return
	}
	if affected, _ := res.RowsAffected(); affected == 0 {
		// Zero rows means either the agent isn't there or the slot is
		// already filled — distinguish so a backfill race reads as the
		// benign conflict it is rather than a missing agent.
		found, ferr := agentExists(r.Context(), h.db, agentID, workspaceID)
		if ferr != nil {
			replyInternalError(w, h.logger, "agent avatar existence check", ferr)
			return
		}
		if !found {
			replyError(w, http.StatusNotFound, "Agent not found")
			return
		}
		replyError(w, http.StatusConflict, "Agent already has a stored avatar; clear it first")
		return
	}

	writeJSON(w, http.StatusOK, map[string]any{"avatar_url": *agentAvatarURL(agentID, hash, workspaceID)})
}

// ServeAvatar streams an agent's stored avatar SVG.
// GET /api/v1/agents/{agentId}/avatar — authed; any workspace member may
// fetch it, since rosters render each other. The ?v= query is ignored (it
// exists purely to bust the browser cache when the bytes change).
func (h *AgentHandler) ServeAvatar(w http.ResponseWriter, r *http.Request) {
	agentID := r.PathValue("agentId")
	workspaceID := WorkspaceIDFromContext(r.Context())

	var svg sql.NullString
	err := h.db.QueryRowContext(r.Context(),
		`SELECT avatar_svg FROM agents WHERE id = ? AND workspace_id = ? AND deleted_at IS NULL`,
		agentID, workspaceID).Scan(&svg)
	if err == sql.ErrNoRows || (err == nil && !svg.Valid) {
		// No stored render is not an error condition — the client just
		// generates from the seed, exactly as it did before this feature.
		replyError(w, http.StatusNotFound, "avatar not found")
		return
	}
	if err != nil {
		replyInternalError(w, h.logger, "read agent avatar", err)
		return
	}

	w.Header().Set("Content-Type", "image/svg+xml")
	w.Header().Set("X-Content-Type-Options", "nosniff")
	// This is the control that makes serving SVG from our own origin safe
	// on direct navigation: no subresource may load and the document is
	// sandboxed into a unique opaque origin, so any active content that
	// got past validateAgentAvatarSVG still cannot reach anything.
	w.Header().Set("Content-Security-Policy", "default-src 'none'; sandbox")
	// Immutable is honest here: the URL carries a content hash, so these
	// bytes never change for this URL. A re-render lands on a new ?v=.
	w.Header().Set("Cache-Control", "private, max-age=31536000, immutable")
	w.WriteHeader(http.StatusOK)
	_, _ = io.WriteString(w, svg.String)
}

// DeleteAvatar drops the stored render, returning the agent to
// generate-from-seed. Also the way to replace an avatar, given PutAvatar's
// write-once rule.
// DELETE /api/v1/agents/{agentId}/avatar
func (h *AgentHandler) DeleteAvatar(w http.ResponseWriter, r *http.Request) {
	agentID := r.PathValue("agentId")
	workspaceID := WorkspaceIDFromContext(r.Context())
	role := RoleFromContext(r.Context())
	user := UserFromContext(r.Context())
	callerUserID := ""
	if user != nil {
		callerUserID = user.ID
	}

	ok, err := canEditAgent(r.Context(), h.db, callerUserID, role, agentID)
	if err != nil {
		replyInternalError(w, h.logger, "agent avatar edit gate", err)
		return
	}
	if !ok {
		replyForbidden(w, h.logger, callerUserID, role, "agent.avatar.delete", "agent:"+agentID)
		return
	}

	// canEditAgent short-circuits to true for OWNER/ADMIN without checking
	// that the agent exists or is in this workspace, so without this an
	// admin would get a cheerful 204 for a typo'd or cross-workspace id and
	// believe they had cleared something. Matches Update/Delete, which both
	// 404 through agentExists.
	found, err := agentExists(r.Context(), h.db, agentID, workspaceID)
	if err != nil {
		replyInternalError(w, h.logger, "agent avatar existence check", err)
		return
	}
	if !found {
		replyError(w, http.StatusNotFound, "Agent not found")
		return
	}

	now := time.Now().UTC().Format(time.RFC3339)
	if _, err := h.db.ExecContext(r.Context(), `
		UPDATE agents SET avatar_svg = NULL, avatar_svg_hash = NULL, updated_at = ?
		WHERE id = ? AND workspace_id = ? AND deleted_at IS NULL`,
		now, agentID, workspaceID); err != nil {
		replyInternalError(w, h.logger, "clear agent avatar", err)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

// agentAvatarInputsChanged reports whether a PATCH body actually repoints
// avatar_seed or avatar_style away from what the row already holds.
//
// Deliberately value-based rather than presence-based: clients routinely
// resubmit unchanged avatar fields alongside an unrelated edit, and treating
// that as a change would throw away the stored render (#1297) on every save.
// A body that omits both keys short-circuits without touching the database.
func agentAvatarInputsChanged(
	ctx context.Context, db *sql.DB, agentID, workspaceID string, body map[string]interface{},
) (bool, error) {
	seedVal, hasSeed := body["avatar_seed"]
	styleVal, hasStyle := body["avatar_style"]
	if !hasSeed && !hasStyle {
		return false, nil
	}

	var curSeed, curStyle sql.NullString
	err := db.QueryRowContext(ctx,
		`SELECT avatar_seed, avatar_style FROM agents
		 WHERE id = ? AND workspace_id = ? AND deleted_at IS NULL`,
		agentID, workspaceID).Scan(&curSeed, &curStyle)
	if err == sql.ErrNoRows {
		// The caller's own existence check reports this; nothing to clear.
		return false, nil
	}
	if err != nil {
		return false, err
	}

	if hasSeed && jsonValueDiffersFromNullString(seedVal, curSeed) {
		return true, nil
	}
	if hasStyle && jsonValueDiffersFromNullString(styleVal, curStyle) {
		return true, nil
	}
	return false, nil
}

// jsonValueDiffersFromNullString compares a decoded JSON value against a
// nullable text column. JSON null and a missing column value are the same
// thing here; anything that isn't a string is treated as a change so an
// unexpected type errs toward re-deriving the avatar rather than keeping a
// render that may no longer match.
func jsonValueDiffersFromNullString(v interface{}, cur sql.NullString) bool {
	if v == nil {
		return cur.Valid
	}
	s, ok := v.(string)
	if !ok {
		return true
	}
	return !cur.Valid || cur.String != s
}
