package api

import (
	"regexp"
	"strings"
)

// The crew icon and colour vocabulary, mirrored from lib/crew-icons.ts. The
// web side owns the drawings; this side only needs the NAMES, to validate
// what the Guide proposes for a crew before the value reaches the crews
// table. crew_icons_test.go parses the TypeScript file and fails the build
// the moment the two lists differ, so this cannot drift silently.
//
// Why validate at all: crew_icon/crew_color are agent-authored fields — the
// Guide chooses them from the marker — and an unknown icon name would render
// as the fallback glyph while an arbitrary colour string would be stored as
// is. Both are refused here (the proposal keeps the template's or the
// default), never trusted.

var crewIconNames = []string{
	"code",
	"shield",
	"megaphone",
	"chart",
	"users",
	"rocket",
	"brain",
	"palette",
	"briefcase",
	"globe",
	"zap",
	"heart",
	"database",
	"lock",
	"bug",
	"network",
	"bot",
	"package",
	"lightbulb",
	"wrench",
	"truck",
	"graduation",
	"phone",
	"send",
	"bell",
	"bookmark",
	"calendar",
	"camera",
	"clipboard",
	"cloud",
	"compass",
	"credit-card",
	"crown",
	"diamond",
	"flame",
	"gift",
	"headphones",
	"home",
	"key",
	"layers",
	"grid",
	"mail",
	"map",
	"monitor",
	"music",
	"newspaper",
	"pen",
	"printer",
	"radio",
	"scale",
	"search",
	"server",
	"settings",
	"cart",
	"star",
	"target",
	"terminal",
	"umbrella",
	"video",
	"wand",
	"wifi",
	"anchor",
	"aperture",
	"archive",
	"award",
	"banknote",
	"battery",
	"bike",
	"binary",
	"blocks",
	"bluetooth",
	"book-open",
	"box",
	"brush",
	"building",
	"building-2",
	"cable",
	"clapperboard",
	"clock",
	"cog",
	"container",
	"cookie",
	"cpu",
	"dice",
	"disc",
	"dollar",
	"dribbble",
	"drum",
	"eye",
	"factory",
	"feather",
	"file-text",
	"fingerprint",
	"flag",
	"folder",
	"gamepad",
	"gauge",
	"globe-2",
	"hand",
	"hash",
	"hard-drive",
	"image",
	"infinity",
	"joystick",
	"landmark",
	"languages",
	"leaf",
	"life-buoy",
	"link",
	"magnet",
	"message",
	"mic",
	"microscope",
	"mountain",
	"paint-bucket",
	"paperclip",
	"percent",
	"pill",
	"pizza",
	"plane",
	"plug",
	"power",
	"qr-code",
	"radar",
	"receipt",
	"repeat",
	"ruler",
	"sailboat",
	"scan",
	"scissors",
	"share",
	"shield-check",
	"shirt",
	"signal",
	"siren",
	"skull",
	"smartphone",
	"sparkles",
	"speaker",
	"stethoscope",
	"sun",
	"swords",
	"tag",
	"tent",
	"thumbs-up",
	"timer",
	"tornado",
	"trophy",
	"tv",
	"university",
	"unplug",
	"upload",
	"utensils",
	"wallet",
	"watch",
	"webcam",
	"wind",
	"activity",
	"airplay",
	"alarm",
	"apple",
	"atom",
	"axe",
	"baby",
	"backpack",
	"badge",
	"badge-check",
	"beaker",
	"bed",
	"beer",
	"bell-ring",
	"bird",
	"blinds",
	"bone",
	"book-marked",
	"brain-circuit",
	"brick-wall",
	"medical",
	"cake",
	"calculator",
	"car",
	"castle",
	"cat",
	"check-circle",
	"cherry",
	"church",
	"citrus",
	"cloud-rain",
	"cloud-sun",
	"clover",
	"code-xml",
	"coffee",
	"coins",
	"component",
	"construction",
	"contact",
	"croissant",
	"crosshair",
	"cuboid",
	"dog",
	"door",
	"dumbbell",
	"ear",
	"earth",
	"eclipse",
	"egg",
	"eraser",
	"fan",
	"fence",
	"ferris-wheel",
	"film",
	"fish",
	"flashlight",
	"flask",
	"flower",
	"footprints",
	"forklift",
	"frame",
	"fuel",
	"gem",
	"ghost",
	"glasses",
	"grape",
	"guitar",
	"hammer",
	"handshake",
	"hard-hat",
	"hop",
	"hospital",
	"hotel",
	"hourglass",
	"ice-cream",
	"inbox",
	"lamp",
	"lamp-desk",
	"laptop",
	"lasso",
	"dashboard",
	"library",
	"ligature",
	"list-music",
	"locate",
	"lollipop",
	"luggage",
	"map-pin",
	"martini",
	"medal",
	"milestone",
	"moon",
	"navigation",
	"nfc",
	"nut",
	"orbit",
	"paint-roller",
	"palm-tree",
	"party",
	"paw",
	"pc",
	"pencil",
	"piggy-bank",
	"pin",
	"takeoff",
	"play",
	"plug-zap",
	"podcast",
	"popcorn",
	"presentation",
	"puzzle",
	"rabbit",
	"rainbow",
	"rat",
	"recycle",
	"refresh",
	"refrigerator",
	"ribbon",
	"rotate-3d",
	"route",
	"rss",
	"satellite",
	"scaling",
	"school",
	"screen-share",
	"scroll",
	"shapes",
	"shell",
	"ship",
	"shopping-bag",
	"shovel",
	"shrub",
	"shuffle",
	"signature",
	"snail",
	"snowflake",
	"sofa",
	"soup",
	"spade",
	"sprout",
	"stamp",
	"store",
	"sunrise",
	"sword",
	"syringe",
	"table",
	"tablet",
	"telescope",
	"test-tube",
	"theater",
	"thermometer",
	"ticket",
	"traffic-cone",
	"train",
	"tree",
	"pine",
	"trending",
	"turtle",
	"type",
	"vault",
	"voicemail",
	"volume",
	"warehouse",
	"waves",
	"wheat",
	"wine",
	"workflow",
	"worm",
	"message-circle",
	"milk-off",
	"minus",
	"more",
	"mouse-pointer",
	"move",
	"panel",
	"replace",
	"trello",
	"triangle",
	"vibrate",
	"slice",
	"space",
	"star-half",
	"sunset",
	"tangent",
	"test-tubes",
	"square-stack",
	"swiss-franc",
	"utensils-crossed",
}

var crewColorPalettes = []string{
	"blue",
	"emerald",
	"violet",
	"amber",
	"rose",
	"cyan",
	"lime",
	"fuchsia",
}

var crewIconSet = func() map[string]bool {
	m := make(map[string]bool, len(crewIconNames))
	for _, n := range crewIconNames {
		m[n] = true
	}
	return m
}()

var crewColorHexRe = regexp.MustCompile(`^#?[0-9a-fA-F]{6}$`)

// validCrewIcon reports whether name is one of the icons the web bundle can
// draw. Case-sensitive on purpose: the names are lowercase-kebab by contract.
func validCrewIcon(name string) bool {
	return crewIconSet[strings.TrimSpace(name)]
}

// normaliseCrewColor returns the stored form of a colour the Guide proposed —
// a palette id as is, a hex with its leading '#' — or "" when it is neither.
func normaliseCrewColor(color string) string {
	color = strings.TrimSpace(color)
	for _, id := range crewColorPalettes {
		if color == id {
			return id
		}
	}
	if crewColorHexRe.MatchString(color) {
		return "#" + strings.TrimPrefix(color, "#")
	}
	return ""
}

// crewIconMenu is the shortlist the Guide's prompt offers — common,
// recognisable, and every one guaranteed to exist in crewIconNames (the test
// checks). The full set is 300+ names, which is a lot of prompt for a choice
// that only has to look right on a card; an icon outside this list is still
// accepted by validCrewIcon, so a Guide that knows a better name may use it.
var crewIconMenu = []string{
	"code", "shield", "megaphone", "chart", "users", "rocket", "brain", "briefcase",
	"globe", "zap", "heart", "search", "eye", "bell", "mail", "calendar",
	"database", "server", "cloud", "lock", "key", "bug", "wrench", "package",
	"truck", "cart", "credit-card", "dollar", "file-text", "book-open",
	"pen", "camera", "image", "music", "video", "map", "home", "building",
	"factory", "flask", "microscope", "activity", "coins", "bookmark",
	"clipboard", "check-circle", "radio", "rss", "layers",
}

func crewIconMenuText() string {
	names := make([]string, 0, len(crewIconMenu))
	for _, n := range crewIconMenu {
		if crewIconSet[n] {
			names = append(names, n)
		}
	}
	return strings.Join(names, ", ")
}
