package api

import (
	_ "embed"
	"net/http"
)

//go:generate go run ../../cmd/gen-openapi

// openAPISpec is generated by cmd/gen-openapi from the r.mux.Handle /
// r.authedMut / r.authedAdmin / r.authedSelfMut route registrations across
// router_*.go — see that command's doc comment for exactly what it does and
// does not capture (paths/methods/path-params are exact; request/response
// bodies are a generic placeholder schema, not hand-authored per endpoint).
// Regenerate with `go generate ./internal/api/` after adding or renaming a
// route.
//
//go:embed openapi.gen.json
var openAPISpec []byte

// ServeOpenAPISpec answers GET /openapi.json with the generated spec as real
// application/json — prior to this the embedded Next.js SPA's catch-all
// answered every unmatched path (including this one) with its index.html, a
// 200 that looked like a working endpoint but carried no schema at all.
func ServeOpenAPISpec(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(openAPISpec)
}

// OpenAPISpecJSON returns the embedded spec so another package can render it —
// internal/apidocs turns it into the browsable pages served at /openapi
// (#1846). The slice backs the embedded data and is shared with every caller,
// including ServeOpenAPISpec: read it, never write to it.
func OpenAPISpecJSON() []byte {
	return openAPISpec
}
