// Command gen-journal-registry generates internal/journal/registry_generated.go
// — AllEntryTypes, the closed list of every journal.EntryType value declared
// or used anywhere in the module — from the source itself.
//
// # Why generated instead of hand-maintained
//
// Before A3 (PRD-ISSUES-AND-ROUTINES-2026 §17), nothing in the codebase
// could answer "is this a real journal entry type" — internal/api/automations.go
// validated event_type against a SHAPE regex only, with a comment admitting
// "the journal has 117 entry types and no exported registry of them". A
// hand-maintained duplicate list would reintroduce exactly that risk one
// commit at a time: someone adds an EntryXxx constant, forgets the second
// list, and the registry silently falls behind again.
//
// # Why the whole module, not just types.go
//
// A3's first cut generated AllEntryTypes from internal/journal/types.go
// alone, on the assumption that every entry type is declared there. That
// assumption was false: at least a dozen types are declared ad hoc in the
// packages that emit them (internal/api/pages_public_tokens.go,
// internal/harbormaster/reward.go, and others), using shapes types.go never
// uses. journalgen.ScanTree reads every non-test .go file under internal/
// and cmd/ and recognises those shapes too — see its doc comment for exactly
// which ones, and the one shape it cannot see soundly.
//
// The remaining risk — someone adds an ad hoc EntryType value and forgets to
// re-run this command before committing — is not a drift the registry can
// protect itself against; internal/journal/registry_generated_test.go
// re-scans the module at test time and fails the build instead.
//
// Run via `go generate ./internal/journal/...` or directly:
//
//	go run ./cmd/gen-journal-registry
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"

	"github.com/crewship-ai/crewship/internal/journalgen"
)

const outputPath = "internal/journal/registry_generated.go"

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gen-journal-registry:", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := journalgen.RepoRoot()
	if err != nil {
		return err
	}

	consts, err := journalgen.ScanTree(root, "internal", "cmd")
	if err != nil {
		return err
	}
	if len(consts) == 0 {
		return fmt.Errorf("scanned %s/{internal,cmd} and found zero EntryType values — that is almost certainly the scanner breaking silently, not the journal losing every entry type", root)
	}

	src, err := render(consts)
	if err != nil {
		return err
	}
	if err := os.WriteFile(root+"/"+outputPath, src, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outputPath, err)
	}
	return nil
}

func render(consts []journalgen.EntryConst) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by cmd/gen-journal-registry from every EntryType value\n")
	b.WriteString("// declared or used under internal/ and cmd/. DO NOT EDIT.\n")
	b.WriteString("// Regenerate with `go generate ./internal/journal/...` after adding, removing\n")
	b.WriteString("// or renaming a journal.EntryType value anywhere in the module, and commit the\n")
	b.WriteString("// result — registry_generated_test.go fails the build if this file falls\n")
	b.WriteString("// behind the source. entryTypeSet and Registered, which used to be generated\n")
	b.WriteString("// alongside this slice, are hand-written in registry.go: unlike the slice\n")
	b.WriteString("// below, their logic never changes when an entry type is added or removed.\n\n")
	b.WriteString("package journal\n\n")

	b.WriteString("// AllEntryTypes lists every journal entry type value found declared or used\n")
	b.WriteString("// as a journal.EntryType under internal/ and cmd/ (see cmd/gen-journal-registry\n")
	b.WriteString("// and internal/journalgen.ScanTree), sorted by value. It is the closed set:\n")
	b.WriteString("// any caller that needs to know whether a string names a real journal entry\n")
	b.WriteString("// type should use Registered, not a shape check — see\n")
	b.WriteString("// internal/api/automations.go's automation event_type validation for the\n")
	b.WriteString("// motivating case (PRD-ISSUES-AND-ROUTINES-2026 §A3).\n")
	b.WriteString("var AllEntryTypes = []EntryType{\n")
	for _, c := range consts {
		if c.InJournalPkg && c.Name != "" {
			b.WriteString("\t" + c.Name + ",\n")
			continue
		}
		// Declared (or only ever used) outside package journal: its Go
		// symbol, if it has one, is either unexported in another package or
		// would need this package to import one that already imports
		// internal/journal — so the literal is the only thing that can
		// appear here.
		b.WriteString(fmt.Sprintf("\tEntryType(%q), // %s\n", c.Value, describeSource(c)))
	}
	b.WriteString("}\n")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt generated source: %w\n---\n%s", err, b.String())
	}
	return formatted, nil
}

func describeSource(c journalgen.EntryConst) string {
	if c.Name != "" {
		return c.Name + ", " + c.Pos
	}
	return c.Pos
}
