// Command gen-journal-registry generates internal/journal/registry_generated.go
// — the closed, exported list of every journal.EntryType declared in
// internal/journal/types.go — from that same source file.
//
// # Why generated instead of hand-maintained
//
// Before A3 (PRD-ISSUES-AND-ROUTINES-2026 §17), nothing in the codebase
// could answer "is this a real journal entry type" — internal/api/automations.go
// validated event_type against a SHAPE regex only, with a comment admitting
// "the journal has 117 entry types and no exported registry of them". A
// hand-maintained duplicate list would reintroduce exactly that risk one
// commit at a time: someone adds an EntryXxx constant, forgets the second
// list, and the registry silently falls behind again.
//
// Generating from types.go removes that failure mode structurally: the
// output can only ever be exactly what the const block says, because that
// is literally where it is read from (see internal/journalgen.Scan). The
// remaining risk — someone edits types.go and forgets to re-run this command
// before committing — is not a drift the registry can protect itself
// against; internal/journal/registry_generated_test.go re-scans types.go at
// test time and fails the build instead.
//
// Run via `go generate ./internal/journal/...` or directly:
//
//	go run ./cmd/gen-journal-registry
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"

	"github.com/crewship-ai/crewship/internal/journalgen"
)

var (
	sourcePath = "internal/journal/types.go"
	outputPath = "internal/journal/registry_generated.go"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gen-journal-registry:", err)
		os.Exit(1)
	}
}

func run() error {
	if _, err := os.Stat(sourcePath); os.IsNotExist(err) {
		// go:generate runs with the package directory as its working
		// directory (internal/journal); direct invocation runs from the
		// repository root. Mirror cmd/gen-openapi's handling of the same
		// ambiguity rather than inventing a second convention.
		if wd, werr := os.Getwd(); werr == nil && filepath.Base(wd) == "journal" {
			sourcePath = "types.go"
			outputPath = "registry_generated.go"
		}
	}

	consts, err := journalgen.Scan(sourcePath)
	if err != nil {
		return err
	}
	if len(consts) == 0 {
		return fmt.Errorf("scanned %s and found zero EntryType constants — that is almost certainly the scanner breaking silently, not the journal losing every entry type", sourcePath)
	}

	src, err := render(consts)
	if err != nil {
		return err
	}
	if err := os.WriteFile(outputPath, src, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outputPath, err)
	}
	return nil
}

func render(consts []journalgen.EntryConst) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by cmd/gen-journal-registry from types.go. DO NOT EDIT.\n")
	b.WriteString("// Regenerate with `go generate ./internal/journal/...` after adding, removing\n")
	b.WriteString("// or renaming an EntryType constant, and commit the result —\n")
	b.WriteString("// registry_generated_test.go fails the build if this file falls behind\n")
	b.WriteString("// types.go.\n\n")
	b.WriteString("package journal\n\n")

	b.WriteString(fmt.Sprintf("// AllEntryTypes lists all %d journal entry types declared in types.go, sorted\n", len(consts)))
	b.WriteString("// by value. It is the closed set: any caller that needs to know whether a\n")
	b.WriteString("// string names a real journal entry type should use Registered, not a shape\n")
	b.WriteString("// check — see internal/api/automations.go's automation event_type validation\n")
	b.WriteString("// for the motivating case (PRD-ISSUES-AND-ROUTINES-2026 §A3).\n")
	b.WriteString("var AllEntryTypes = []EntryType{\n")
	for _, c := range consts {
		b.WriteString("\t" + c.Name + ",\n")
	}
	b.WriteString("}\n\n")

	b.WriteString("// entryTypeSet is the O(1) membership index behind Registered, built once at\n")
	b.WriteString("// package init from AllEntryTypes.\n")
	b.WriteString("var entryTypeSet = func() map[EntryType]struct{} {\n")
	b.WriteString("\tm := make(map[EntryType]struct{}, len(AllEntryTypes))\n")
	b.WriteString("\tfor _, t := range AllEntryTypes {\n")
	b.WriteString("\t\tm[t] = struct{}{}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn m\n")
	b.WriteString("}()\n\n")

	b.WriteString("// Registered reports whether t is one of the closed set of journal entry\n")
	b.WriteString("// types declared in types.go. A caller taking an event type from outside the\n")
	b.WriteString("// process — an automation, a webhook filter, a CLI flag — should reject\n")
	b.WriteString("// anything this returns false for: an unregistered type looks shaped like a\n")
	b.WriteString("// real one and will never fire, silently.\n")
	b.WriteString("func Registered(t EntryType) bool {\n")
	b.WriteString("\t_, ok := entryTypeSet[t]\n")
	b.WriteString("\treturn ok\n")
	b.WriteString("}\n")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt generated source: %w\n---\n%s", err, b.String())
	}
	return formatted, nil
}
