import React,{useEffect,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {usePageSnapshot,runAction,getActionStatus} from '@crewship/pages'
import './style.css'
function App(){
 const page=usePageSnapshot();const memory=page?.panels.find(p=>p.id==='memory');const data=memory?.data as {value:number;sparkline:number[]}|undefined
 const controlPanel=page?.panels.find(p=>p.id==='control')?.data as {items?:{state:string}[]}|undefined
 const configured=controlPanel?.items?.[0]?.state==='ok'
 const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [pending,setPending]=useState('')
 useEffect(()=>{if(!pending)return;let alive=true;const expires=Date.now()+30000;const giveUp=()=>{if(!alive)return;setPending('');setBusy(false);setMessage('Run status is unknown after 30 seconds. Refresh the Page or try again. See Routines → History.')};const poll=async()=>{if(Date.now()>expires)return giveUp();try{const r=await getActionStatus(pending);if(!alive)return;const status=r.run_status||r.pending_status;if(['completed','failed','cancelled','expired','interrupted'].includes(status)){setPending('');setBusy(false);setMessage(status==='completed'?'Control action completed. Watch the measurement timestamp below.':'Control action failed. See Routines → History for the error.')}}catch{if(alive)setMessage('Cannot read run status. Check Routines → History.')}};void poll();const timer=setInterval(poll,2000);return()=>{alive=false;clearInterval(timer)}},[pending])
 async function control(id:string){if(busy)return;setBusy(true);try{const r=await runAction('control',id);setPending(r.pending_id);setMessage('Control action queued. Waiting for execution…')}catch(e){setBusy(false);setMessage(e instanceof Error?e.message:'The action failed.')}}

 return <main className="demo"><div className="topline"><span className="brand"><b>C</b><strong>CREWSHIP</strong><i>/</i>LIVE LAB</span><span className="tag">REAL CONTAINER DATA</span></div><header className="hero"><div><div className="eyebrow">A SCRIPT THAT KEEPS WORKING</div><h1>Inside the container.</h1><p>One Python process reads memory every five seconds and publishes directly to this Page. Start a 15-minute session and watch the timestamp change.</p></div><div className="hero-signal"><span>CONTAINER MEMORY</span><strong>{data?`${data.value} MB`:'No sample yet'}</strong><small>{memory?.state==='fresh'?'Live measurement':'Stopped or waiting for a new sample'}</small></div></header><nav className="toolbar"><button className="story-action" disabled={busy||!configured} onClick={()=>void control('start')}>Start live monitor</button><button className="story-action" disabled={busy||!configured} onClick={()=>void control('stop')}>Stop monitor</button></nav>{!configured&&<p className="action-status">Live monitoring is not configured. Run the seed again to configure the scoped Page callback.</p>}{message&&<p role="status" className="action-status">{message}</p>}<article className="panel"><span className="eyebrow">LAST 20 MEASUREMENTS</span><div className="bars">{data?.sparkline.map((v,i)=><i key={i} style={{height:`${Math.max(15,v/Math.max(...data.sparkline,1)*100)}%`}}/>)}</div><p>Last received: {memory?.producedAt?new Date(memory.producedAt).toLocaleTimeString():'Start the monitor to receive live data'}</p></article><aside className="source-note"><strong>Replace this script with your own collector</strong><p>Use the same pattern for a database check, a local service or a machine sensor. This example samples its own container, so it sends no traffic to public sites.</p><details><summary>Inspect the example</summary><p>/crew/shared/demo/business/live.py runs inside Operations. The start routine launches one process; file locking prevents duplicates. A scoped webhook can write only this Page’s memory panel. The process stops after 15 minutes or when you press Stop.</p></details></aside></main>
}
createRoot(document.getElementById('root')!).render(<App/> )
