// Code generated by cmd/gen-journal-registry from types.go. DO NOT EDIT.
// Regenerate with `go generate ./internal/journal/...` after adding, removing
// or renaming an EntryType constant, and commit the result —
// registry_generated_test.go fails the build if this file falls behind
// types.go.

package journal

// AllEntryTypes lists all 129 journal entry types declared in types.go, sorted
// by value. It is the closed set: any caller that needs to know whether a
// string names a real journal entry type should use Registered, not a shape
// check — see internal/api/automations.go's automation event_type validation
// for the motivating case (PRD-ISSUES-AND-ROUTINES-2026 §A3).
var AllEntryTypes = []EntryType{
	EntryAgentError,
	EntryAgentMentioned,
	EntryAgentStatus,
	EntryApprovalCancelled,
	EntryApprovalDenied,
	EntryApprovalGranted,
	EntryApprovalRequest,
	EntryApprovalTimeout,
	EntryTrustGranted,
	EntryTrustRevoked,
	EntryAssignmentDone,
	EntryAssignmentCreate,
	EntryAssignmentFail,
	EntryAssignmentRun,
	EntryAuditEntityCreated,
	EntryAuditEntityDeleted,
	EntryAuditEntityRestored,
	EntryAuditEntityUpdated,
	EntryAutomationDepthExceeded,
	EntryAutomationThrottled,
	EntryBackupChainResigned,
	EntryBudgetExceed,
	EntryBudgetWarning,
	EntryChatAgentResponse,
	EntryChatUserMessage,
	EntryCheckpointCreated,
	EntryCheckpointRestored,
	EntryContainerMetrics,
	EntryContainerSnapshot,
	EntryConversationCompacted,
	EntryCostIncurred,
	EntryCredentialAutoAssignEmpty,
	EntryCredentialAutoAssignFailed,
	EntryCredentialLeaseIssued,
	EntryCredentialRevealPolicy,
	EntryCredentialRevealed,
	EntryCredentialSensitivityLowered,
	EntryCrewAction,
	EntryEvalMetric,
	EntryEvalRegression,
	EntryEvalRunStarted,
	EntryExecCommand,
	EntryExecOutputChunk,
	EntryFileWritten,
	EntryForkCreated,
	EntryGuardrailInput,
	EntryGuardrailOutput,
	EntryHookBlocked,
	EntryHookDispatchError,
	EntryHookFired,
	EntryImageStale,
	EntryKeeperDecision,
	EntryKeeperRequest,
	EntryLLMCacheHit,
	EntryLLMCall,
	EntryMemoryConfigUpdated,
	EntryMemoryConsolidated,
	EntryMemoryConsolidationProposed,
	EntryMemoryPriorityChanged,
	EntryMemorySearched,
	EntryMemorySkillApproved,
	EntryMemorySkillProposed,
	EntryMemorySkillRejected,
	EntryMemoryUpdated,
	EntryMemoryVersionsSwept,
	EntryMemoryWriteRejected,
	EntryMemoryWriteVerifierBlocked,
	EntryMessageBroadcast,
	EntryMissionAssigned,
	EntryMissionComment,
	EntryMissionCreated,
	EntryMissionStatus,
	EntryNetworkEgress,
	EntryNetworkPortClose,
	EntryNetworkPortOpen,
	EntryNotificationDelivered,
	EntryNotificationDropped,
	EntryNotificationFailed,
	EntryPageActionDispatched,
	EntryPageGrantAdded,
	EntryPageGrantRemoved,
	EntryPagePanelRecovered,
	EntryPagePanelStale,
	EntryPagePanelUpdated,
	EntryPageProduceDenied,
	EntryPageSpecChanged,
	EntryPageWakeFired,
	EntryPeerConversation,
	EntryPeerEscalation,
	EntryPipelineDryRun,
	EntryPipelineRunCompleted,
	EntryPipelineRunFailed,
	EntryPipelineRunStarted,
	EntryPipelineRunsSwept,
	EntryPipelineScheduleCircuitBreaker,
	EntryPipelineScheduleMissedOccurrences,
	EntryPipelineStepCompleted,
	EntryPipelineStepContainerReady,
	EntryPipelineStepFailed,
	EntryPipelineStepRetrying,
	EntryPipelineStepSkipped,
	EntryPipelineStepStarted,
	EntryPipelineStepValidation,
	EntryProvisioningBuildFailed,
	EntryProvisioningBuilding,
	EntryProvisioningComplete,
	EntryProvisioningFailed,
	EntryProvisioningQueued,
	EntryProvisioningStep,
	EntryRunAgentSpan,
	EntryRunCancelled,
	EntryRunCompleted,
	EntryRunFailed,
	EntryRunSessionInit,
	EntryRunStarted,
	EntryRunTimeout,
	EntrySidecarStale,
	EntrySkillAssigned,
	EntrySkillDeleted,
	EntrySkillImported,
	EntrySkillInvoked,
	EntrySkillUnassigned,
	EntrySummaryGenerated,
	EntrySystemCompaction,
	EntrySystemConsolidationCompleted,
	EntrySystemConsolidationTriggered,
	EntrySystemHookToggled,
	EntrySystemMigration,
	EntryTaskDelegated,
}

// entryTypeSet is the O(1) membership index behind Registered, built once at
// package init from AllEntryTypes.
var entryTypeSet = func() map[EntryType]struct{} {
	m := make(map[EntryType]struct{}, len(AllEntryTypes))
	for _, t := range AllEntryTypes {
		m[t] = struct{}{}
	}
	return m
}()

// Registered reports whether t is one of the closed set of journal entry
// types declared in types.go. A caller taking an event type from outside the
// process — an automation, a webhook filter, a CLI flag — should reject
// anything this returns false for: an unregistered type looks shaped like a
// real one and will never fire, silently.
func Registered(t EntryType) bool {
	_, ok := entryTypeSet[t]
	return ok
}
