#!/usr/bin/env bash
set -euo pipefail

# Regenerate THIRD-PARTY-NOTICES.md from current go.mod dependencies using
# go-licenses (github.com/google/go-licenses).
#
# Run via: make notices
# Or directly: ./scripts/gen-notices.sh
#
# Crewship itself is Apache-2.0. This file lists all Go dependencies
# (direct + transitive) of the `crewship` binary and their licenses.

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

# Ensure go-licenses is installed
if ! command -v go-licenses >/dev/null 2>&1; then
  # Try $HOME/go/bin (common GOPATH location)
  if [ -x "$HOME/go/bin/go-licenses" ]; then
    export PATH="$PATH:$HOME/go/bin"
  else
    echo "Installing go-licenses..."
    go install github.com/google/go-licenses@latest
    export PATH="$PATH:$HOME/go/bin"
  fi
fi

# Create embed stub so go-licenses can analyze packages importing web/embed.go
if [ ! -f web/out/index.html ]; then
  mkdir -p web/out
  echo '<!doctype html>' > web/out/index.html
fi

# modernc.org/mathutil is BSD-3-Clause but its LICENSE file has a format
# go-licenses doesn't detect. Known issue, documented in DEPENDENCIES.md.
# The --ignore flag excludes it from the check but it still appears in the list.
OUTPUT="THIRD-PARTY-NOTICES.md"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  cat <<'HEADER'
# Third-Party Notices

Crewship itself is licensed under Apache-2.0 — see [LICENSE](./LICENSE).

This file lists all Go dependencies (direct and transitive) of the `crewship`
binary and their licenses. It is auto-generated by `make notices` using
[go-licenses](https://github.com/google/go-licenses). Do not edit by hand —
re-run `make notices` after any dependency change.

**Known exception:** `modernc.org/mathutil` is BSD-3-Clause (verified in its
`LICENSE` file) but `go-licenses` cannot auto-detect it due to a file-matching
edge case. It is excluded from the automated check and listed manually below.

## Dependencies

| Package | License | Source URL |
|---------|---------|------------|
HEADER

  go-licenses csv ./cmd/crewship 2>/dev/null \
    | awk -F',' 'NF>=3 {printf "| `%s` | %s | %s |\n", $1, $3, $2}' \
    | sort -u

  cat <<'MANUAL'

## Manually verified

| Package | License | Source URL |
|---------|---------|------------|
| `modernc.org/mathutil` | BSD-3-Clause | https://gitlab.com/cznic/mathutil |

## Known accepted vulnerabilities

These vulnerabilities are tracked but cannot be fixed via dependency upgrade
because no upstream fix is available. They are accepted as known risk and
monitored for upstream resolution.

| CVE | Module | Status | Notes |
|-----|--------|--------|-------|
| GO-2026-4887 | github.com/docker/docker | No upstream fix | AuthZ plugin bypass on oversized request bodies. Not reachable via Crewship's usage pattern (we do not use AuthZ plugins). Monitor https://pkg.go.dev/vuln/GO-2026-4887 |
| GO-2026-4883 | github.com/docker/docker | No upstream fix | Off-by-one in plugin privilege validation. Not reachable via Crewship's usage pattern. Monitor https://pkg.go.dev/vuln/GO-2026-4883 |
MANUAL
} > "$TMP"

mv "$TMP" "$OUTPUT"
echo "✓ $OUTPUT regenerated"
